import type { StoreItem } from '@/types'

/**
 * Catálogo de la TIENDA (generado). 558 ítems. Fuente única en
 * código; el seed SQL (store_items) se genera del mismo listado, así el costo
 * que valida el servidor y lo que ve el cliente siempre coinciden.
 * Kinds equipables en Focus Pet: pet, hat, outfit, accessory.
 */
export const EQUIPPABLE_KINDS = ['pet', 'hat', 'outfit', 'accessory'] as const

export const STORE_CATALOG: StoreItem[] = [
  {"id":"gato","name":"Gato","kind":"pet","emoji":"🐱","cost":0},
  {"id":"perro","name":"Perro","kind":"pet","emoji":"🐶","cost":0},
  {"id":"zorro","name":"Zorro","kind":"pet","emoji":"🦊","cost":80},
  {"id":"buho","name":"Búho","kind":"pet","emoji":"🦉","cost":120},
  {"id":"dragon","name":"Dragón","kind":"pet","emoji":"🐉","cost":300},
  {"id":"gorro","name":"Gorro","kind":"hat","emoji":"🎩","cost":30},
  {"id":"corona","name":"Corona","kind":"hat","emoji":"👑","cost":150},
  {"id":"bufanda","name":"Bufanda","kind":"outfit","emoji":"🧣","cost":40},
  {"id":"capa","name":"Capa","kind":"outfit","emoji":"🦸","cost":120},
  {"id":"gafas","name":"Gafas","kind":"accessory","emoji":"🕶️","cost":25},
  {"id":"medalla","name":"Medalla","kind":"accessory","emoji":"🏅","cost":60},
  {"id":"pet-0","name":"Ascua Mascota","kind":"pet","emoji":"🐰","cost":0},
  {"id":"pet-1","name":"Forja Mascota","kind":"pet","emoji":"🐹","cost":0},
  {"id":"pet-2","name":"Brasa Mascota","kind":"pet","emoji":"🐭","cost":20},
  {"id":"pet-3","name":"Yunque Mascota","kind":"pet","emoji":"🐻","cost":40},
  {"id":"pet-4","name":"Carbón Mascota","kind":"pet","emoji":"🐼","cost":40},
  {"id":"pet-5","name":"Acero Mascota","kind":"pet","emoji":"🐨","cost":40},
  {"id":"pet-6","name":"Ígneo Mascota","kind":"pet","emoji":"🐯","cost":60},
  {"id":"pet-7","name":"Rúnico Mascota","kind":"pet","emoji":"🦁","cost":60},
  {"id":"pet-8","name":"Místico Mascota","kind":"pet","emoji":"🐮","cost":60},
  {"id":"pet-9","name":"Solar Mascota","kind":"pet","emoji":"🐷","cost":90},
  {"id":"pet-10","name":"Lunar Mascota","kind":"pet","emoji":"🐸","cost":90},
  {"id":"pet-11","name":"Estelar Mascota","kind":"pet","emoji":"🐵","cost":90},
  {"id":"pet-12","name":"Sombrío Mascota","kind":"pet","emoji":"🐔","cost":120},
  {"id":"pet-13","name":"Dorado Mascota","kind":"pet","emoji":"🐧","cost":120},
  {"id":"pet-14","name":"Carmesí Mascota","kind":"pet","emoji":"🐦","cost":120},
  {"id":"pet-15","name":"Ébano Mascota","kind":"pet","emoji":"🦆","cost":160},
  {"id":"pet-16","name":"Cristal Mascota","kind":"pet","emoji":"🦅","cost":160},
  {"id":"pet-17","name":"Fénix Mascota","kind":"pet","emoji":"🦇","cost":160},
  {"id":"pet-18","name":"Titán Mascota","kind":"pet","emoji":"🐺","cost":220},
  {"id":"pet-19","name":"Obsidiana Mascota","kind":"pet","emoji":"🐗","cost":220},
  {"id":"pet-20","name":"Ascua Mascota 2","kind":"pet","emoji":"🐴","cost":220},
  {"id":"pet-21","name":"Forja Mascota 2","kind":"pet","emoji":"🦄","cost":300},
  {"id":"pet-22","name":"Brasa Mascota 2","kind":"pet","emoji":"🐝","cost":300},
  {"id":"pet-23","name":"Yunque Mascota 2","kind":"pet","emoji":"🦋","cost":300},
  {"id":"pet-24","name":"Carbón Mascota 2","kind":"pet","emoji":"🐌","cost":400},
  {"id":"pet-25","name":"Acero Mascota 2","kind":"pet","emoji":"🐞","cost":400},
  {"id":"pet-26","name":"Ígneo Mascota 2","kind":"pet","emoji":"🐢","cost":400},
  {"id":"pet-27","name":"Rúnico Mascota 2","kind":"pet","emoji":"🐍","cost":400},
  {"id":"pet-28","name":"Místico Mascota 2","kind":"pet","emoji":"🦎","cost":400},
  {"id":"pet-29","name":"Solar Mascota 2","kind":"pet","emoji":"🐙","cost":400},
  {"id":"pet-30","name":"Lunar Mascota 2","kind":"pet","emoji":"🦑","cost":400},
  {"id":"pet-31","name":"Estelar Mascota 2","kind":"pet","emoji":"🦀","cost":400},
  {"id":"pet-32","name":"Sombrío Mascota 2","kind":"pet","emoji":"🦞","cost":400},
  {"id":"pet-33","name":"Dorado Mascota 2","kind":"pet","emoji":"🐠","cost":400},
  {"id":"pet-34","name":"Carmesí Mascota 2","kind":"pet","emoji":"🐟","cost":400},
  {"id":"pet-35","name":"Ébano Mascota 2","kind":"pet","emoji":"🐡","cost":400},
  {"id":"pet-36","name":"Cristal Mascota 2","kind":"pet","emoji":"🐬","cost":400},
  {"id":"pet-37","name":"Fénix Mascota 2","kind":"pet","emoji":"🐳","cost":400},
  {"id":"pet-38","name":"Titán Mascota 2","kind":"pet","emoji":"🐋","cost":400},
  {"id":"pet-39","name":"Obsidiana Mascota 2","kind":"pet","emoji":"🦈","cost":400},
  {"id":"pet-40","name":"Ascua Mascota 3","kind":"pet","emoji":"🐆","cost":400},
  {"id":"pet-41","name":"Forja Mascota 3","kind":"pet","emoji":"🐅","cost":400},
  {"id":"pet-42","name":"Brasa Mascota 3","kind":"pet","emoji":"🦓","cost":400},
  {"id":"pet-43","name":"Yunque Mascota 3","kind":"pet","emoji":"🦍","cost":400},
  {"id":"pet-44","name":"Carbón Mascota 3","kind":"pet","emoji":"🐘","cost":400},
  {"id":"pet-45","name":"Acero Mascota 3","kind":"pet","emoji":"🦛","cost":400},
  {"id":"pet-46","name":"Ígneo Mascota 3","kind":"pet","emoji":"🦏","cost":400},
  {"id":"pet-47","name":"Rúnico Mascota 3","kind":"pet","emoji":"🐪","cost":400},
  {"id":"pet-48","name":"Místico Mascota 3","kind":"pet","emoji":"🐫","cost":400},
  {"id":"pet-49","name":"Solar Mascota 3","kind":"pet","emoji":"🦒","cost":400},
  {"id":"pet-50","name":"Lunar Mascota 3","kind":"pet","emoji":"🦘","cost":400},
  {"id":"pet-51","name":"Estelar Mascota 3","kind":"pet","emoji":"🐂","cost":400},
  {"id":"pet-52","name":"Sombrío Mascota 3","kind":"pet","emoji":"🐄","cost":400},
  {"id":"pet-53","name":"Dorado Mascota 3","kind":"pet","emoji":"🐎","cost":400},
  {"id":"pet-54","name":"Carmesí Mascota 3","kind":"pet","emoji":"🐖","cost":400},
  {"id":"pet-55","name":"Ébano Mascota 3","kind":"pet","emoji":"🐏","cost":400},
  {"id":"pet-56","name":"Cristal Mascota 3","kind":"pet","emoji":"🐑","cost":400},
  {"id":"pet-57","name":"Fénix Mascota 3","kind":"pet","emoji":"🦙","cost":400},
  {"id":"pet-58","name":"Titán Mascota 3","kind":"pet","emoji":"🐐","cost":400},
  {"id":"pet-59","name":"Obsidiana Mascota 3","kind":"pet","emoji":"🦌","cost":400},
  {"id":"pet-60","name":"Ascua Mascota 4","kind":"pet","emoji":"🐩","cost":400},
  {"id":"pet-61","name":"Forja Mascota 4","kind":"pet","emoji":"🦝","cost":400},
  {"id":"pet-62","name":"Brasa Mascota 4","kind":"pet","emoji":"🦨","cost":400},
  {"id":"pet-63","name":"Yunque Mascota 4","kind":"pet","emoji":"🦡","cost":400},
  {"id":"pet-64","name":"Carbón Mascota 4","kind":"pet","emoji":"🦦","cost":400},
  {"id":"pet-65","name":"Acero Mascota 4","kind":"pet","emoji":"🦥","cost":400},
  {"id":"pet-66","name":"Ígneo Mascota 4","kind":"pet","emoji":"🐿️","cost":400},
  {"id":"pet-67","name":"Rúnico Mascota 4","kind":"pet","emoji":"🦔","cost":400},
  {"id":"pet-68","name":"Místico Mascota 4","kind":"pet","emoji":"🦚","cost":400},
  {"id":"pet-69","name":"Solar Mascota 4","kind":"pet","emoji":"🦜","cost":400},
  {"id":"pet-70","name":"Lunar Mascota 4","kind":"pet","emoji":"🦢","cost":400},
  {"id":"pet-71","name":"Estelar Mascota 4","kind":"pet","emoji":"🦩","cost":400},
  {"id":"pet-72","name":"Sombrío Mascota 4","kind":"pet","emoji":"🕊️","cost":400},
  {"id":"pet-73","name":"Dorado Mascota 4","kind":"pet","emoji":"🐇","cost":400},
  {"id":"hat-0","name":"Ascua Gorro","kind":"hat","emoji":"🎓","cost":20},
  {"id":"hat-1","name":"Forja Gorro","kind":"hat","emoji":"⛑️","cost":20},
  {"id":"hat-2","name":"Brasa Gorro","kind":"hat","emoji":"🪖","cost":20},
  {"id":"hat-3","name":"Yunque Gorro","kind":"hat","emoji":"🧢","cost":40},
  {"id":"hat-4","name":"Carbón Gorro","kind":"hat","emoji":"👒","cost":40},
  {"id":"hat-5","name":"Acero Gorro","kind":"hat","emoji":"🎃","cost":40},
  {"id":"hat-6","name":"Ígneo Gorro","kind":"hat","emoji":"🥽","cost":60},
  {"id":"hat-7","name":"Rúnico Gorro","kind":"hat","emoji":"🎀","cost":60},
  {"id":"hat-8","name":"Místico Gorro","kind":"hat","emoji":"👽","cost":60},
  {"id":"hat-9","name":"Solar Gorro","kind":"hat","emoji":"🤖","cost":90},
  {"id":"hat-10","name":"Lunar Gorro","kind":"hat","emoji":"🧠","cost":90},
  {"id":"hat-11","name":"Estelar Gorro","kind":"hat","emoji":"🌸","cost":90},
  {"id":"hat-12","name":"Sombrío Gorro","kind":"hat","emoji":"🌺","cost":120},
  {"id":"hat-13","name":"Dorado Gorro","kind":"hat","emoji":"🌻","cost":120},
  {"id":"hat-14","name":"Carmesí Gorro","kind":"hat","emoji":"🍄","cost":120},
  {"id":"hat-15","name":"Ébano Gorro","kind":"hat","emoji":"⭐","cost":160},
  {"id":"hat-16","name":"Cristal Gorro","kind":"hat","emoji":"✨","cost":160},
  {"id":"hat-17","name":"Fénix Gorro","kind":"hat","emoji":"💫","cost":160},
  {"id":"hat-18","name":"Titán Gorro","kind":"hat","emoji":"🔥","cost":220},
  {"id":"hat-19","name":"Obsidiana Gorro","kind":"hat","emoji":"❄️","cost":220},
  {"id":"hat-20","name":"Ascua Gorro 2","kind":"hat","emoji":"😇","cost":220},
  {"id":"hat-21","name":"Forja Gorro 2","kind":"hat","emoji":"👼","cost":300},
  {"id":"hat-22","name":"Brasa Gorro 2","kind":"hat","emoji":"🧙","cost":300},
  {"id":"hat-23","name":"Yunque Gorro 2","kind":"hat","emoji":"🧛","cost":300},
  {"id":"hat-24","name":"Carbón Gorro 2","kind":"hat","emoji":"🧜","cost":400},
  {"id":"hat-25","name":"Acero Gorro 2","kind":"hat","emoji":"🧚","cost":400},
  {"id":"hat-26","name":"Ígneo Gorro 2","kind":"hat","emoji":"👺","cost":400},
  {"id":"hat-27","name":"Rúnico Gorro 2","kind":"hat","emoji":"👹","cost":400},
  {"id":"hat-28","name":"Místico Gorro 2","kind":"hat","emoji":"🤠","cost":400},
  {"id":"hat-29","name":"Solar Gorro 2","kind":"hat","emoji":"🥷","cost":400},
  {"id":"hat-30","name":"Lunar Gorro 2","kind":"hat","emoji":"🎅","cost":400},
  {"id":"hat-31","name":"Estelar Gorro 2","kind":"hat","emoji":"🤶","cost":400},
  {"id":"outfit-0","name":"Ascua Atuendo","kind":"outfit","emoji":"🥼","cost":20},
  {"id":"outfit-1","name":"Forja Atuendo","kind":"outfit","emoji":"🥋","cost":20},
  {"id":"outfit-2","name":"Brasa Atuendo","kind":"outfit","emoji":"👔","cost":20},
  {"id":"outfit-3","name":"Yunque Atuendo","kind":"outfit","emoji":"👕","cost":40},
  {"id":"outfit-4","name":"Carbón Atuendo","kind":"outfit","emoji":"👗","cost":40},
  {"id":"outfit-5","name":"Acero Atuendo","kind":"outfit","emoji":"👘","cost":40},
  {"id":"outfit-6","name":"Ígneo Atuendo","kind":"outfit","emoji":"🥻","cost":60},
  {"id":"outfit-7","name":"Rúnico Atuendo","kind":"outfit","emoji":"🩱","cost":60},
  {"id":"outfit-8","name":"Místico Atuendo","kind":"outfit","emoji":"👙","cost":60},
  {"id":"outfit-9","name":"Solar Atuendo","kind":"outfit","emoji":"👚","cost":90},
  {"id":"outfit-10","name":"Lunar Atuendo","kind":"outfit","emoji":"🧥","cost":90},
  {"id":"outfit-11","name":"Estelar Atuendo","kind":"outfit","emoji":"🩳","cost":90},
  {"id":"outfit-12","name":"Sombrío Atuendo","kind":"outfit","emoji":"👖","cost":120},
  {"id":"outfit-13","name":"Dorado Atuendo","kind":"outfit","emoji":"🎽","cost":120},
  {"id":"outfit-14","name":"Carmesí Atuendo","kind":"outfit","emoji":"🦺","cost":120},
  {"id":"outfit-15","name":"Ébano Atuendo","kind":"outfit","emoji":"🧦","cost":160},
  {"id":"outfit-16","name":"Cristal Atuendo","kind":"outfit","emoji":"🩲","cost":160},
  {"id":"outfit-17","name":"Fénix Atuendo","kind":"outfit","emoji":"👛","cost":160},
  {"id":"outfit-18","name":"Titán Atuendo","kind":"outfit","emoji":"👜","cost":220},
  {"id":"outfit-19","name":"Obsidiana Atuendo","kind":"outfit","emoji":"🎒","cost":220},
  {"id":"outfit-20","name":"Ascua Atuendo 2","kind":"outfit","emoji":"🧤","cost":220},
  {"id":"outfit-21","name":"Forja Atuendo 2","kind":"outfit","emoji":"🌈","cost":300},
  {"id":"outfit-22","name":"Brasa Atuendo 2","kind":"outfit","emoji":"🔰","cost":300},
  {"id":"outfit-23","name":"Yunque Atuendo 2","kind":"outfit","emoji":"🏵️","cost":300},
  {"id":"accessory-0","name":"Ascua Accesorio","kind":"accessory","emoji":"👓","cost":20},
  {"id":"accessory-1","name":"Forja Accesorio","kind":"accessory","emoji":"🥇","cost":20},
  {"id":"accessory-2","name":"Brasa Accesorio","kind":"accessory","emoji":"🥈","cost":20},
  {"id":"accessory-3","name":"Yunque Accesorio","kind":"accessory","emoji":"🥉","cost":40},
  {"id":"accessory-4","name":"Carbón Accesorio","kind":"accessory","emoji":"💍","cost":40},
  {"id":"accessory-5","name":"Acero Accesorio","kind":"accessory","emoji":"📿","cost":40},
  {"id":"accessory-6","name":"Ígneo Accesorio","kind":"accessory","emoji":"💎","cost":60},
  {"id":"accessory-7","name":"Rúnico Accesorio","kind":"accessory","emoji":"🔮","cost":60},
  {"id":"accessory-8","name":"Místico Accesorio","kind":"accessory","emoji":"⌚","cost":60},
  {"id":"accessory-9","name":"Solar Accesorio","kind":"accessory","emoji":"📱","cost":90},
  {"id":"accessory-10","name":"Lunar Accesorio","kind":"accessory","emoji":"🎧","cost":90},
  {"id":"accessory-11","name":"Estelar Accesorio","kind":"accessory","emoji":"🎮","cost":90},
  {"id":"accessory-12","name":"Sombrío Accesorio","kind":"accessory","emoji":"🕹️","cost":120},
  {"id":"accessory-13","name":"Dorado Accesorio","kind":"accessory","emoji":"🎲","cost":120},
  {"id":"accessory-14","name":"Carmesí Accesorio","kind":"accessory","emoji":"🃏","cost":120},
  {"id":"accessory-15","name":"Ébano Accesorio","kind":"accessory","emoji":"🎯","cost":160},
  {"id":"accessory-16","name":"Cristal Accesorio","kind":"accessory","emoji":"🪄","cost":160},
  {"id":"accessory-17","name":"Fénix Accesorio","kind":"accessory","emoji":"🗡️","cost":160},
  {"id":"accessory-18","name":"Titán Accesorio","kind":"accessory","emoji":"🛡️","cost":220},
  {"id":"accessory-19","name":"Obsidiana Accesorio","kind":"accessory","emoji":"⚔️","cost":220},
  {"id":"accessory-20","name":"Ascua Accesorio 2","kind":"accessory","emoji":"🏹","cost":220},
  {"id":"accessory-21","name":"Forja Accesorio 2","kind":"accessory","emoji":"🔱","cost":300},
  {"id":"accessory-22","name":"Brasa Accesorio 2","kind":"accessory","emoji":"⚜️","cost":300},
  {"id":"accessory-23","name":"Yunque Accesorio 2","kind":"accessory","emoji":"🎖️","cost":300},
  {"id":"aura-0","name":"Ascua Aura","kind":"aura","emoji":"🌟","cost":20},
  {"id":"aura-1","name":"Forja Aura","kind":"aura","emoji":"💥","cost":20},
  {"id":"aura-2","name":"Brasa Aura","kind":"aura","emoji":"⚡","cost":20},
  {"id":"aura-3","name":"Yunque Aura","kind":"aura","emoji":"🌊","cost":40},
  {"id":"aura-4","name":"Carbón Aura","kind":"aura","emoji":"💨","cost":40},
  {"id":"aura-5","name":"Acero Aura","kind":"aura","emoji":"🌀","cost":40},
  {"id":"aura-6","name":"Ígneo Aura","kind":"aura","emoji":"🌪️","cost":60},
  {"id":"aura-7","name":"Rúnico Aura","kind":"aura","emoji":"🫧","cost":60},
  {"id":"aura-8","name":"Místico Aura","kind":"aura","emoji":"💧","cost":60},
  {"id":"aura-9","name":"Solar Aura","kind":"aura","emoji":"🩸","cost":90},
  {"id":"aura-10","name":"Lunar Aura","kind":"aura","emoji":"☄️","cost":90},
  {"id":"aura-11","name":"Estelar Aura","kind":"aura","emoji":"🌠","cost":90},
  {"id":"aura-12","name":"Sombrío Aura","kind":"aura","emoji":"🎆","cost":120},
  {"id":"aura-13","name":"Dorado Aura","kind":"aura","emoji":"🎇","cost":120},
  {"id":"aura-14","name":"Carmesí Aura","kind":"aura","emoji":"🕯️","cost":120},
  {"id":"aura-15","name":"Ébano Aura","kind":"aura","emoji":"💠","cost":160},
  {"id":"aura-16","name":"Cristal Aura","kind":"aura","emoji":"🔆","cost":160},
  {"id":"aura-17","name":"Fénix Aura","kind":"aura","emoji":"🔅","cost":160},
  {"id":"aura-18","name":"Titán Aura","kind":"aura","emoji":"♨️","cost":220},
  {"id":"fondo-0","name":"Ascua Fondo","kind":"fondo","emoji":"🌋","cost":20},
  {"id":"fondo-1","name":"Forja Fondo","kind":"fondo","emoji":"🏔️","cost":20},
  {"id":"fondo-2","name":"Brasa Fondo","kind":"fondo","emoji":"⛰️","cost":20},
  {"id":"fondo-3","name":"Yunque Fondo","kind":"fondo","emoji":"🌌","cost":40},
  {"id":"fondo-4","name":"Carbón Fondo","kind":"fondo","emoji":"🏞️","cost":40},
  {"id":"fondo-5","name":"Acero Fondo","kind":"fondo","emoji":"🏜️","cost":40},
  {"id":"fondo-6","name":"Ígneo Fondo","kind":"fondo","emoji":"🌇","cost":60},
  {"id":"fondo-7","name":"Rúnico Fondo","kind":"fondo","emoji":"🌆","cost":60},
  {"id":"fondo-8","name":"Místico Fondo","kind":"fondo","emoji":"🏙️","cost":60},
  {"id":"fondo-9","name":"Solar Fondo","kind":"fondo","emoji":"🌃","cost":90},
  {"id":"fondo-10","name":"Lunar Fondo","kind":"fondo","emoji":"🌉","cost":90},
  {"id":"fondo-11","name":"Estelar Fondo","kind":"fondo","emoji":"🏝️","cost":90},
  {"id":"fondo-12","name":"Sombrío Fondo","kind":"fondo","emoji":"🏕️","cost":120},
  {"id":"fondo-13","name":"Dorado Fondo","kind":"fondo","emoji":"🏰","cost":120},
  {"id":"fondo-14","name":"Carmesí Fondo","kind":"fondo","emoji":"🏯","cost":120},
  {"id":"fondo-15","name":"Ébano Fondo","kind":"fondo","emoji":"🗼","cost":160},
  {"id":"fondo-16","name":"Cristal Fondo","kind":"fondo","emoji":"🌅","cost":160},
  {"id":"fondo-17","name":"Fénix Fondo","kind":"fondo","emoji":"🌄","cost":160},
  {"id":"fondo-18","name":"Titán Fondo","kind":"fondo","emoji":"🌁","cost":220},
  {"id":"fondo-19","name":"Obsidiana Fondo","kind":"fondo","emoji":"🪐","cost":220},
  {"id":"fondo-20","name":"Ascua Fondo 2","kind":"fondo","emoji":"🌏","cost":220},
  {"id":"fondo-21","name":"Forja Fondo 2","kind":"fondo","emoji":"🌙","cost":300},
  {"id":"insignia-0","name":"Ascua Insignia","kind":"insignia","emoji":"🏆","cost":20},
  {"id":"insignia-1","name":"Forja Insignia","kind":"insignia","emoji":"💯","cost":20},
  {"id":"insignia-2","name":"Brasa Insignia","kind":"insignia","emoji":"🎗️","cost":20},
  {"id":"insignia-3","name":"Yunque Insignia","kind":"insignia","emoji":"♠️","cost":40},
  {"id":"insignia-4","name":"Carbón Insignia","kind":"insignia","emoji":"♥️","cost":40},
  {"id":"insignia-5","name":"Acero Insignia","kind":"insignia","emoji":"♦️","cost":40},
  {"id":"insignia-6","name":"Ígneo Insignia","kind":"insignia","emoji":"♣️","cost":60},
  {"id":"insignia-7","name":"Rúnico Insignia","kind":"insignia","emoji":"🀄","cost":60},
  {"id":"insignia-8","name":"Místico Insignia","kind":"insignia","emoji":"☯️","cost":60},
  {"id":"insignia-9","name":"Solar Insignia","kind":"insignia","emoji":"🕉️","cost":90},
  {"id":"insignia-10","name":"Lunar Insignia","kind":"insignia","emoji":"✝️","cost":90},
  {"id":"insignia-11","name":"Estelar Insignia","kind":"insignia","emoji":"☪️","cost":90},
  {"id":"insignia-12","name":"Sombrío Insignia","kind":"insignia","emoji":"🔯","cost":120},
  {"id":"insignia-13","name":"Dorado Insignia","kind":"insignia","emoji":"🛐","cost":120},
  {"id":"insignia-14","name":"Carmesí Insignia","kind":"insignia","emoji":"⚛️","cost":120},
  {"id":"comida-0","name":"Ascua Manjar","kind":"comida","emoji":"🍎","cost":20},
  {"id":"comida-1","name":"Forja Manjar","kind":"comida","emoji":"🍕","cost":20},
  {"id":"comida-2","name":"Brasa Manjar","kind":"comida","emoji":"🍔","cost":20},
  {"id":"comida-3","name":"Yunque Manjar","kind":"comida","emoji":"🍟","cost":40},
  {"id":"comida-4","name":"Carbón Manjar","kind":"comida","emoji":"🌭","cost":40},
  {"id":"comida-5","name":"Acero Manjar","kind":"comida","emoji":"🍿","cost":40},
  {"id":"comida-6","name":"Ígneo Manjar","kind":"comida","emoji":"🧂","cost":60},
  {"id":"comida-7","name":"Rúnico Manjar","kind":"comida","emoji":"🥓","cost":60},
  {"id":"comida-8","name":"Místico Manjar","kind":"comida","emoji":"🥞","cost":60},
  {"id":"comida-9","name":"Solar Manjar","kind":"comida","emoji":"🧇","cost":90},
  {"id":"comida-10","name":"Lunar Manjar","kind":"comida","emoji":"🍳","cost":90},
  {"id":"comida-11","name":"Estelar Manjar","kind":"comida","emoji":"🥚","cost":90},
  {"id":"comida-12","name":"Sombrío Manjar","kind":"comida","emoji":"🧀","cost":120},
  {"id":"comida-13","name":"Dorado Manjar","kind":"comida","emoji":"🥨","cost":120},
  {"id":"comida-14","name":"Carmesí Manjar","kind":"comida","emoji":"🥐","cost":120},
  {"id":"comida-15","name":"Ébano Manjar","kind":"comida","emoji":"🥖","cost":160},
  {"id":"comida-16","name":"Cristal Manjar","kind":"comida","emoji":"🍞","cost":160},
  {"id":"comida-17","name":"Fénix Manjar","kind":"comida","emoji":"🥯","cost":160},
  {"id":"comida-18","name":"Titán Manjar","kind":"comida","emoji":"🍜","cost":220},
  {"id":"comida-19","name":"Obsidiana Manjar","kind":"comida","emoji":"🍲","cost":220},
  {"id":"comida-20","name":"Ascua Manjar 2","kind":"comida","emoji":"🍛","cost":220},
  {"id":"comida-21","name":"Forja Manjar 2","kind":"comida","emoji":"🍤","cost":300},
  {"id":"comida-22","name":"Brasa Manjar 2","kind":"comida","emoji":"🍙","cost":300},
  {"id":"comida-23","name":"Yunque Manjar 2","kind":"comida","emoji":"🍚","cost":300},
  {"id":"comida-24","name":"Carbón Manjar 2","kind":"comida","emoji":"🍘","cost":400},
  {"id":"comida-25","name":"Acero Manjar 2","kind":"comida","emoji":"🍢","cost":400},
  {"id":"comida-26","name":"Ígneo Manjar 2","kind":"comida","emoji":"🍡","cost":400},
  {"id":"comida-27","name":"Rúnico Manjar 2","kind":"comida","emoji":"🍧","cost":400},
  {"id":"comida-28","name":"Místico Manjar 2","kind":"comida","emoji":"🍨","cost":400},
  {"id":"comida-29","name":"Solar Manjar 2","kind":"comida","emoji":"🍦","cost":400},
  {"id":"comida-30","name":"Lunar Manjar 2","kind":"comida","emoji":"🥧","cost":400},
  {"id":"comida-31","name":"Estelar Manjar 2","kind":"comida","emoji":"🧁","cost":400},
  {"id":"comida-32","name":"Sombrío Manjar 2","kind":"comida","emoji":"🍰","cost":400},
  {"id":"comida-33","name":"Dorado Manjar 2","kind":"comida","emoji":"🎂","cost":400},
  {"id":"comida-34","name":"Carmesí Manjar 2","kind":"comida","emoji":"🍮","cost":400},
  {"id":"comida-35","name":"Ébano Manjar 2","kind":"comida","emoji":"🍭","cost":400},
  {"id":"comida-36","name":"Cristal Manjar 2","kind":"comida","emoji":"🍬","cost":400},
  {"id":"comida-37","name":"Fénix Manjar 2","kind":"comida","emoji":"🍫","cost":400},
  {"id":"comida-38","name":"Titán Manjar 2","kind":"comida","emoji":"🍩","cost":400},
  {"id":"comida-39","name":"Obsidiana Manjar 2","kind":"comida","emoji":"🍪","cost":400},
  {"id":"comida-40","name":"Ascua Manjar 3","kind":"comida","emoji":"🌰","cost":400},
  {"id":"comida-41","name":"Forja Manjar 3","kind":"comida","emoji":"🥜","cost":400},
  {"id":"comida-42","name":"Brasa Manjar 3","kind":"comida","emoji":"🍯","cost":400},
  {"id":"comida-43","name":"Yunque Manjar 3","kind":"comida","emoji":"🥛","cost":400},
  {"id":"comida-44","name":"Carbón Manjar 3","kind":"comida","emoji":"☕","cost":400},
  {"id":"comida-45","name":"Acero Manjar 3","kind":"comida","emoji":"🍵","cost":400},
  {"id":"comida-46","name":"Ígneo Manjar 3","kind":"comida","emoji":"🧃","cost":400},
  {"id":"comida-47","name":"Rúnico Manjar 3","kind":"comida","emoji":"🥤","cost":400},
  {"id":"comida-48","name":"Místico Manjar 3","kind":"comida","emoji":"🧋","cost":400},
  {"id":"comida-49","name":"Solar Manjar 3","kind":"comida","emoji":"🍺","cost":400},
  {"id":"comida-50","name":"Lunar Manjar 3","kind":"comida","emoji":"🍷","cost":400},
  {"id":"comida-51","name":"Estelar Manjar 3","kind":"comida","emoji":"🥂","cost":400},
  {"id":"comida-52","name":"Sombrío Manjar 3","kind":"comida","emoji":"🍸","cost":400},
  {"id":"comida-53","name":"Dorado Manjar 3","kind":"comida","emoji":"🍹","cost":400},
  {"id":"comida-54","name":"Carmesí Manjar 3","kind":"comida","emoji":"🌮","cost":400},
  {"id":"comida-55","name":"Ébano Manjar 3","kind":"comida","emoji":"🌯","cost":400},
  {"id":"comida-56","name":"Cristal Manjar 3","kind":"comida","emoji":"🫔","cost":400},
  {"id":"comida-57","name":"Fénix Manjar 3","kind":"comida","emoji":"🥙","cost":400},
  {"id":"comida-58","name":"Titán Manjar 3","kind":"comida","emoji":"🧆","cost":400},
  {"id":"comida-59","name":"Obsidiana Manjar 3","kind":"comida","emoji":"🍣","cost":400},
  {"id":"comida-60","name":"Ascua Manjar 4","kind":"comida","emoji":"🍱","cost":400},
  {"id":"comida-61","name":"Forja Manjar 4","kind":"comida","emoji":"🍇","cost":400},
  {"id":"comida-62","name":"Brasa Manjar 4","kind":"comida","emoji":"🍈","cost":400},
  {"id":"comida-63","name":"Yunque Manjar 4","kind":"comida","emoji":"🍉","cost":400},
  {"id":"comida-64","name":"Carbón Manjar 4","kind":"comida","emoji":"🍊","cost":400},
  {"id":"comida-65","name":"Acero Manjar 4","kind":"comida","emoji":"🍋","cost":400},
  {"id":"comida-66","name":"Ígneo Manjar 4","kind":"comida","emoji":"🍌","cost":400},
  {"id":"comida-67","name":"Rúnico Manjar 4","kind":"comida","emoji":"🍍","cost":400},
  {"id":"comida-68","name":"Místico Manjar 4","kind":"comida","emoji":"🥭","cost":400},
  {"id":"comida-69","name":"Solar Manjar 4","kind":"comida","emoji":"🍐","cost":400},
  {"id":"comida-70","name":"Lunar Manjar 4","kind":"comida","emoji":"🍑","cost":400},
  {"id":"comida-71","name":"Estelar Manjar 4","kind":"comida","emoji":"🍒","cost":400},
  {"id":"comida-72","name":"Sombrío Manjar 4","kind":"comida","emoji":"🍓","cost":400},
  {"id":"comida-73","name":"Dorado Manjar 4","kind":"comida","emoji":"🫐","cost":400},
  {"id":"comida-74","name":"Carmesí Manjar 4","kind":"comida","emoji":"🥝","cost":400},
  {"id":"comida-75","name":"Ébano Manjar 4","kind":"comida","emoji":"🍅","cost":400},
  {"id":"comida-76","name":"Cristal Manjar 4","kind":"comida","emoji":"🫒","cost":400},
  {"id":"comida-77","name":"Fénix Manjar 4","kind":"comida","emoji":"🥥","cost":400},
  {"id":"comida-78","name":"Titán Manjar 4","kind":"comida","emoji":"🥑","cost":400},
  {"id":"comida-79","name":"Obsidiana Manjar 4","kind":"comida","emoji":"🍆","cost":400},
  {"id":"comida-80","name":"Ascua Manjar 5","kind":"comida","emoji":"🥔","cost":400},
  {"id":"comida-81","name":"Forja Manjar 5","kind":"comida","emoji":"🥕","cost":400},
  {"id":"comida-82","name":"Brasa Manjar 5","kind":"comida","emoji":"🌽","cost":400},
  {"id":"comida-83","name":"Yunque Manjar 5","kind":"comida","emoji":"🌶️","cost":400},
  {"id":"comida-84","name":"Carbón Manjar 5","kind":"comida","emoji":"🫑","cost":400},
  {"id":"comida-85","name":"Acero Manjar 5","kind":"comida","emoji":"🥒","cost":400},
  {"id":"comida-86","name":"Ígneo Manjar 5","kind":"comida","emoji":"🥬","cost":400},
  {"id":"comida-87","name":"Rúnico Manjar 5","kind":"comida","emoji":"🥦","cost":400},
  {"id":"comida-88","name":"Místico Manjar 5","kind":"comida","emoji":"🧄","cost":400},
  {"id":"comida-89","name":"Solar Manjar 5","kind":"comida","emoji":"🧅","cost":400},
  {"id":"planta-0","name":"Ascua Planta","kind":"planta","emoji":"🌱","cost":20},
  {"id":"planta-1","name":"Forja Planta","kind":"planta","emoji":"🌿","cost":20},
  {"id":"planta-2","name":"Brasa Planta","kind":"planta","emoji":"🍀","cost":20},
  {"id":"planta-3","name":"Yunque Planta","kind":"planta","emoji":"🌾","cost":40},
  {"id":"planta-4","name":"Carbón Planta","kind":"planta","emoji":"🌵","cost":40},
  {"id":"planta-5","name":"Acero Planta","kind":"planta","emoji":"🌴","cost":40},
  {"id":"planta-6","name":"Ígneo Planta","kind":"planta","emoji":"🌲","cost":60},
  {"id":"planta-7","name":"Rúnico Planta","kind":"planta","emoji":"🌳","cost":60},
  {"id":"planta-8","name":"Místico Planta","kind":"planta","emoji":"🎋","cost":60},
  {"id":"planta-9","name":"Solar Planta","kind":"planta","emoji":"🎍","cost":90},
  {"id":"planta-10","name":"Lunar Planta","kind":"planta","emoji":"🍁","cost":90},
  {"id":"planta-11","name":"Estelar Planta","kind":"planta","emoji":"🍂","cost":90},
  {"id":"planta-12","name":"Sombrío Planta","kind":"planta","emoji":"🍃","cost":120},
  {"id":"planta-13","name":"Dorado Planta","kind":"planta","emoji":"🌷","cost":120},
  {"id":"planta-14","name":"Carmesí Planta","kind":"planta","emoji":"🌹","cost":120},
  {"id":"planta-15","name":"Ébano Planta","kind":"planta","emoji":"🥀","cost":160},
  {"id":"planta-16","name":"Cristal Planta","kind":"planta","emoji":"🌼","cost":160},
  {"id":"planta-17","name":"Fénix Planta","kind":"planta","emoji":"💐","cost":160},
  {"id":"planta-18","name":"Titán Planta","kind":"planta","emoji":"🪴","cost":220},
  {"id":"deporte-0","name":"Ascua Deporte","kind":"deporte","emoji":"⚽","cost":20},
  {"id":"deporte-1","name":"Forja Deporte","kind":"deporte","emoji":"🏀","cost":20},
  {"id":"deporte-2","name":"Brasa Deporte","kind":"deporte","emoji":"🏈","cost":20},
  {"id":"deporte-3","name":"Yunque Deporte","kind":"deporte","emoji":"⚾","cost":40},
  {"id":"deporte-4","name":"Carbón Deporte","kind":"deporte","emoji":"🥎","cost":40},
  {"id":"deporte-5","name":"Acero Deporte","kind":"deporte","emoji":"🎾","cost":40},
  {"id":"deporte-6","name":"Ígneo Deporte","kind":"deporte","emoji":"🏐","cost":60},
  {"id":"deporte-7","name":"Rúnico Deporte","kind":"deporte","emoji":"🏉","cost":60},
  {"id":"deporte-8","name":"Místico Deporte","kind":"deporte","emoji":"🥏","cost":60},
  {"id":"deporte-9","name":"Solar Deporte","kind":"deporte","emoji":"🎱","cost":90},
  {"id":"deporte-10","name":"Lunar Deporte","kind":"deporte","emoji":"🪀","cost":90},
  {"id":"deporte-11","name":"Estelar Deporte","kind":"deporte","emoji":"🏓","cost":90},
  {"id":"deporte-12","name":"Sombrío Deporte","kind":"deporte","emoji":"🏸","cost":120},
  {"id":"deporte-13","name":"Dorado Deporte","kind":"deporte","emoji":"🥅","cost":120},
  {"id":"deporte-14","name":"Carmesí Deporte","kind":"deporte","emoji":"🏒","cost":120},
  {"id":"deporte-15","name":"Ébano Deporte","kind":"deporte","emoji":"🏑","cost":160},
  {"id":"deporte-16","name":"Cristal Deporte","kind":"deporte","emoji":"🥍","cost":160},
  {"id":"deporte-17","name":"Fénix Deporte","kind":"deporte","emoji":"🏏","cost":160},
  {"id":"deporte-18","name":"Titán Deporte","kind":"deporte","emoji":"🪃","cost":220},
  {"id":"deporte-19","name":"Obsidiana Deporte","kind":"deporte","emoji":"🥊","cost":220},
  {"id":"deporte-20","name":"Ascua Deporte 2","kind":"deporte","emoji":"🛹","cost":220},
  {"id":"deporte-21","name":"Forja Deporte 2","kind":"deporte","emoji":"🛼","cost":300},
  {"id":"deporte-22","name":"Brasa Deporte 2","kind":"deporte","emoji":"🛷","cost":300},
  {"id":"deporte-23","name":"Yunque Deporte 2","kind":"deporte","emoji":"⛸️","cost":300},
  {"id":"deporte-24","name":"Carbón Deporte 2","kind":"deporte","emoji":"🥌","cost":400},
  {"id":"deporte-25","name":"Acero Deporte 2","kind":"deporte","emoji":"🎿","cost":400},
  {"id":"deporte-26","name":"Ígneo Deporte 2","kind":"deporte","emoji":"⛷️","cost":400},
  {"id":"deporte-27","name":"Rúnico Deporte 2","kind":"deporte","emoji":"🏂","cost":400},
  {"id":"deporte-28","name":"Místico Deporte 2","kind":"deporte","emoji":"🏋️","cost":400},
  {"id":"deporte-29","name":"Solar Deporte 2","kind":"deporte","emoji":"🤼","cost":400},
  {"id":"deporte-30","name":"Lunar Deporte 2","kind":"deporte","emoji":"🤸","cost":400},
  {"id":"deporte-31","name":"Estelar Deporte 2","kind":"deporte","emoji":"🤺","cost":400},
  {"id":"deporte-32","name":"Sombrío Deporte 2","kind":"deporte","emoji":"🤾","cost":400},
  {"id":"deporte-33","name":"Dorado Deporte 2","kind":"deporte","emoji":"🏌️","cost":400},
  {"id":"deporte-34","name":"Carmesí Deporte 2","kind":"deporte","emoji":"🏇","cost":400},
  {"id":"deporte-35","name":"Ébano Deporte 2","kind":"deporte","emoji":"🧘","cost":400},
  {"id":"deporte-36","name":"Cristal Deporte 2","kind":"deporte","emoji":"🏄","cost":400},
  {"id":"deporte-37","name":"Fénix Deporte 2","kind":"deporte","emoji":"🏊","cost":400},
  {"id":"deporte-38","name":"Titán Deporte 2","kind":"deporte","emoji":"🤽","cost":400},
  {"id":"deporte-39","name":"Obsidiana Deporte 2","kind":"deporte","emoji":"🚣","cost":400},
  {"id":"deporte-40","name":"Ascua Deporte 3","kind":"deporte","emoji":"🧗","cost":400},
  {"id":"deporte-41","name":"Forja Deporte 3","kind":"deporte","emoji":"🚵","cost":400},
  {"id":"deporte-42","name":"Brasa Deporte 3","kind":"deporte","emoji":"🚴","cost":400},
  {"id":"musica-0","name":"Ascua Nota","kind":"musica","emoji":"🎵","cost":20},
  {"id":"musica-1","name":"Forja Nota","kind":"musica","emoji":"🎶","cost":20},
  {"id":"musica-2","name":"Brasa Nota","kind":"musica","emoji":"🎼","cost":20},
  {"id":"musica-3","name":"Yunque Nota","kind":"musica","emoji":"🎤","cost":40},
  {"id":"musica-4","name":"Carbón Nota","kind":"musica","emoji":"🎷","cost":40},
  {"id":"musica-5","name":"Acero Nota","kind":"musica","emoji":"🎸","cost":40},
  {"id":"musica-6","name":"Ígneo Nota","kind":"musica","emoji":"🎹","cost":60},
  {"id":"musica-7","name":"Rúnico Nota","kind":"musica","emoji":"🎺","cost":60},
  {"id":"musica-8","name":"Místico Nota","kind":"musica","emoji":"🎻","cost":60},
  {"id":"musica-9","name":"Solar Nota","kind":"musica","emoji":"🪕","cost":90},
  {"id":"musica-10","name":"Lunar Nota","kind":"musica","emoji":"🥁","cost":90},
  {"id":"musica-11","name":"Estelar Nota","kind":"musica","emoji":"🪘","cost":90},
  {"id":"musica-12","name":"Sombrío Nota","kind":"musica","emoji":"📯","cost":120},
  {"id":"musica-13","name":"Dorado Nota","kind":"musica","emoji":"🎙️","cost":120},
  {"id":"musica-14","name":"Carmesí Nota","kind":"musica","emoji":"🎚️","cost":120},
  {"id":"musica-15","name":"Ébano Nota","kind":"musica","emoji":"🎛️","cost":160},
  {"id":"objeto-0","name":"Ascua Objeto","kind":"objeto","emoji":"💡","cost":20},
  {"id":"objeto-1","name":"Forja Objeto","kind":"objeto","emoji":"🔦","cost":20},
  {"id":"objeto-2","name":"Brasa Objeto","kind":"objeto","emoji":"🪔","cost":20},
  {"id":"objeto-3","name":"Yunque Objeto","kind":"objeto","emoji":"🔧","cost":40},
  {"id":"objeto-4","name":"Carbón Objeto","kind":"objeto","emoji":"🔨","cost":40},
  {"id":"objeto-5","name":"Acero Objeto","kind":"objeto","emoji":"⚒️","cost":40},
  {"id":"objeto-6","name":"Ígneo Objeto","kind":"objeto","emoji":"🛠️","cost":60},
  {"id":"objeto-7","name":"Rúnico Objeto","kind":"objeto","emoji":"⛏️","cost":60},
  {"id":"objeto-8","name":"Místico Objeto","kind":"objeto","emoji":"🔩","cost":60},
  {"id":"objeto-9","name":"Solar Objeto","kind":"objeto","emoji":"⚙️","cost":90},
  {"id":"objeto-10","name":"Lunar Objeto","kind":"objeto","emoji":"🧰","cost":90},
  {"id":"objeto-11","name":"Estelar Objeto","kind":"objeto","emoji":"🧲","cost":90},
  {"id":"objeto-12","name":"Sombrío Objeto","kind":"objeto","emoji":"🔫","cost":120},
  {"id":"objeto-13","name":"Dorado Objeto","kind":"objeto","emoji":"💣","cost":120},
  {"id":"objeto-14","name":"Carmesí Objeto","kind":"objeto","emoji":"🧨","cost":120},
  {"id":"objeto-15","name":"Ébano Objeto","kind":"objeto","emoji":"🪓","cost":160},
  {"id":"objeto-16","name":"Cristal Objeto","kind":"objeto","emoji":"🔪","cost":160},
  {"id":"objeto-17","name":"Fénix Objeto","kind":"objeto","emoji":"🚬","cost":160},
  {"id":"objeto-18","name":"Titán Objeto","kind":"objeto","emoji":"⚰️","cost":220},
  {"id":"objeto-19","name":"Obsidiana Objeto","kind":"objeto","emoji":"⚱️","cost":220},
  {"id":"objeto-20","name":"Ascua Objeto 2","kind":"objeto","emoji":"🏺","cost":220},
  {"id":"objeto-21","name":"Forja Objeto 2","kind":"objeto","emoji":"🧿","cost":300},
  {"id":"objeto-22","name":"Brasa Objeto 2","kind":"objeto","emoji":"💈","cost":300},
  {"id":"objeto-23","name":"Yunque Objeto 2","kind":"objeto","emoji":"⚗️","cost":300},
  {"id":"objeto-24","name":"Carbón Objeto 2","kind":"objeto","emoji":"🔭","cost":400},
  {"id":"objeto-25","name":"Acero Objeto 2","kind":"objeto","emoji":"🔬","cost":400},
  {"id":"objeto-26","name":"Ígneo Objeto 2","kind":"objeto","emoji":"🕳️","cost":400},
  {"id":"objeto-27","name":"Rúnico Objeto 2","kind":"objeto","emoji":"💊","cost":400},
  {"id":"objeto-28","name":"Místico Objeto 2","kind":"objeto","emoji":"💉","cost":400},
  {"id":"objeto-29","name":"Solar Objeto 2","kind":"objeto","emoji":"🧬","cost":400},
  {"id":"objeto-30","name":"Lunar Objeto 2","kind":"objeto","emoji":"🦠","cost":400},
  {"id":"objeto-31","name":"Estelar Objeto 2","kind":"objeto","emoji":"🧫","cost":400},
  {"id":"objeto-32","name":"Sombrío Objeto 2","kind":"objeto","emoji":"🧪","cost":400},
  {"id":"objeto-33","name":"Dorado Objeto 2","kind":"objeto","emoji":"🌡️","cost":400},
  {"id":"objeto-34","name":"Carmesí Objeto 2","kind":"objeto","emoji":"🧹","cost":400},
  {"id":"objeto-35","name":"Ébano Objeto 2","kind":"objeto","emoji":"🧺","cost":400},
  {"id":"objeto-36","name":"Cristal Objeto 2","kind":"objeto","emoji":"🧻","cost":400},
  {"id":"objeto-37","name":"Fénix Objeto 2","kind":"objeto","emoji":"🛎️","cost":400},
  {"id":"objeto-38","name":"Titán Objeto 2","kind":"objeto","emoji":"🔑","cost":400},
  {"id":"objeto-39","name":"Obsidiana Objeto 2","kind":"objeto","emoji":"🗝️","cost":400},
  {"id":"objeto-40","name":"Ascua Objeto 3","kind":"objeto","emoji":"🚪","cost":400},
  {"id":"objeto-41","name":"Forja Objeto 3","kind":"objeto","emoji":"🪑","cost":400},
  {"id":"objeto-42","name":"Brasa Objeto 3","kind":"objeto","emoji":"🛋️","cost":400},
  {"id":"objeto-43","name":"Yunque Objeto 3","kind":"objeto","emoji":"🛏️","cost":400},
  {"id":"objeto-44","name":"Carbón Objeto 3","kind":"objeto","emoji":"🧸","cost":400},
  {"id":"objeto-45","name":"Acero Objeto 3","kind":"objeto","emoji":"🖼️","cost":400},
  {"id":"objeto-46","name":"Ígneo Objeto 3","kind":"objeto","emoji":"🪞","cost":400},
  {"id":"objeto-47","name":"Rúnico Objeto 3","kind":"objeto","emoji":"🛍️","cost":400},
  {"id":"objeto-48","name":"Místico Objeto 3","kind":"objeto","emoji":"🛒","cost":400},
  {"id":"objeto-49","name":"Solar Objeto 3","kind":"objeto","emoji":"🎁","cost":400},
  {"id":"objeto-50","name":"Lunar Objeto 3","kind":"objeto","emoji":"🎈","cost":400},
  {"id":"objeto-51","name":"Estelar Objeto 3","kind":"objeto","emoji":"🎏","cost":400},
  {"id":"objeto-52","name":"Sombrío Objeto 3","kind":"objeto","emoji":"🎊","cost":400},
  {"id":"objeto-53","name":"Dorado Objeto 3","kind":"objeto","emoji":"🎉","cost":400},
  {"id":"objeto-54","name":"Carmesí Objeto 3","kind":"objeto","emoji":"🪅","cost":400},
  {"id":"objeto-55","name":"Ébano Objeto 3","kind":"objeto","emoji":"🪆","cost":400},
  {"id":"objeto-56","name":"Cristal Objeto 3","kind":"objeto","emoji":"📷","cost":400},
  {"id":"objeto-57","name":"Fénix Objeto 3","kind":"objeto","emoji":"📸","cost":400},
  {"id":"objeto-58","name":"Titán Objeto 3","kind":"objeto","emoji":"📹","cost":400},
  {"id":"objeto-59","name":"Obsidiana Objeto 3","kind":"objeto","emoji":"📼","cost":400},
  {"id":"objeto-60","name":"Ascua Objeto 4","kind":"objeto","emoji":"💾","cost":400},
  {"id":"objeto-61","name":"Forja Objeto 4","kind":"objeto","emoji":"💿","cost":400},
  {"id":"objeto-62","name":"Brasa Objeto 4","kind":"objeto","emoji":"📀","cost":400},
  {"id":"objeto-63","name":"Yunque Objeto 4","kind":"objeto","emoji":"🧮","cost":400},
  {"id":"objeto-64","name":"Carbón Objeto 4","kind":"objeto","emoji":"📕","cost":400},
  {"id":"objeto-65","name":"Acero Objeto 4","kind":"objeto","emoji":"📗","cost":400},
  {"id":"objeto-66","name":"Ígneo Objeto 4","kind":"objeto","emoji":"📘","cost":400},
  {"id":"objeto-67","name":"Rúnico Objeto 4","kind":"objeto","emoji":"📙","cost":400},
  {"id":"objeto-68","name":"Místico Objeto 4","kind":"objeto","emoji":"📚","cost":400},
  {"id":"objeto-69","name":"Solar Objeto 4","kind":"objeto","emoji":"📖","cost":400},
  {"id":"vehiculo-0","name":"Ascua Vehículo","kind":"vehiculo","emoji":"🚗","cost":20},
  {"id":"vehiculo-1","name":"Forja Vehículo","kind":"vehiculo","emoji":"🚕","cost":20},
  {"id":"vehiculo-2","name":"Brasa Vehículo","kind":"vehiculo","emoji":"🚙","cost":20},
  {"id":"vehiculo-3","name":"Yunque Vehículo","kind":"vehiculo","emoji":"🚌","cost":40},
  {"id":"vehiculo-4","name":"Carbón Vehículo","kind":"vehiculo","emoji":"🚎","cost":40},
  {"id":"vehiculo-5","name":"Acero Vehículo","kind":"vehiculo","emoji":"🏎️","cost":40},
  {"id":"vehiculo-6","name":"Ígneo Vehículo","kind":"vehiculo","emoji":"🚓","cost":60},
  {"id":"vehiculo-7","name":"Rúnico Vehículo","kind":"vehiculo","emoji":"🚑","cost":60},
  {"id":"vehiculo-8","name":"Místico Vehículo","kind":"vehiculo","emoji":"🚒","cost":60},
  {"id":"vehiculo-9","name":"Solar Vehículo","kind":"vehiculo","emoji":"🚐","cost":90},
  {"id":"vehiculo-10","name":"Lunar Vehículo","kind":"vehiculo","emoji":"🚚","cost":90},
  {"id":"vehiculo-11","name":"Estelar Vehículo","kind":"vehiculo","emoji":"🚛","cost":90},
  {"id":"vehiculo-12","name":"Sombrío Vehículo","kind":"vehiculo","emoji":"🚜","cost":120},
  {"id":"vehiculo-13","name":"Dorado Vehículo","kind":"vehiculo","emoji":"🛻","cost":120},
  {"id":"vehiculo-14","name":"Carmesí Vehículo","kind":"vehiculo","emoji":"🏍️","cost":120},
  {"id":"vehiculo-15","name":"Ébano Vehículo","kind":"vehiculo","emoji":"🛵","cost":160},
  {"id":"vehiculo-16","name":"Cristal Vehículo","kind":"vehiculo","emoji":"🚲","cost":160},
  {"id":"vehiculo-17","name":"Fénix Vehículo","kind":"vehiculo","emoji":"🛴","cost":160},
  {"id":"vehiculo-18","name":"Titán Vehículo","kind":"vehiculo","emoji":"🚨","cost":220},
  {"id":"vehiculo-19","name":"Obsidiana Vehículo","kind":"vehiculo","emoji":"🚔","cost":220},
  {"id":"vehiculo-20","name":"Ascua Vehículo 2","kind":"vehiculo","emoji":"🚍","cost":220},
  {"id":"vehiculo-21","name":"Forja Vehículo 2","kind":"vehiculo","emoji":"🚘","cost":300},
  {"id":"vehiculo-22","name":"Brasa Vehículo 2","kind":"vehiculo","emoji":"🚖","cost":300},
  {"id":"vehiculo-23","name":"Yunque Vehículo 2","kind":"vehiculo","emoji":"🚡","cost":300},
  {"id":"vehiculo-24","name":"Carbón Vehículo 2","kind":"vehiculo","emoji":"🚠","cost":400},
  {"id":"vehiculo-25","name":"Acero Vehículo 2","kind":"vehiculo","emoji":"🚟","cost":400},
  {"id":"vehiculo-26","name":"Ígneo Vehículo 2","kind":"vehiculo","emoji":"🚃","cost":400},
  {"id":"vehiculo-27","name":"Rúnico Vehículo 2","kind":"vehiculo","emoji":"🚋","cost":400},
  {"id":"vehiculo-28","name":"Místico Vehículo 2","kind":"vehiculo","emoji":"🚞","cost":400},
  {"id":"vehiculo-29","name":"Solar Vehículo 2","kind":"vehiculo","emoji":"🚝","cost":400},
  {"id":"vehiculo-30","name":"Lunar Vehículo 2","kind":"vehiculo","emoji":"🚄","cost":400},
  {"id":"vehiculo-31","name":"Estelar Vehículo 2","kind":"vehiculo","emoji":"🚅","cost":400},
  {"id":"vehiculo-32","name":"Sombrío Vehículo 2","kind":"vehiculo","emoji":"🚈","cost":400},
  {"id":"vehiculo-33","name":"Dorado Vehículo 2","kind":"vehiculo","emoji":"🚂","cost":400},
  {"id":"vehiculo-34","name":"Carmesí Vehículo 2","kind":"vehiculo","emoji":"🚆","cost":400},
  {"id":"vehiculo-35","name":"Ébano Vehículo 2","kind":"vehiculo","emoji":"🚇","cost":400},
  {"id":"vehiculo-36","name":"Cristal Vehículo 2","kind":"vehiculo","emoji":"🚊","cost":400},
  {"id":"vehiculo-37","name":"Fénix Vehículo 2","kind":"vehiculo","emoji":"🚉","cost":400},
  {"id":"vehiculo-38","name":"Titán Vehículo 2","kind":"vehiculo","emoji":"✈️","cost":400},
  {"id":"vehiculo-39","name":"Obsidiana Vehículo 2","kind":"vehiculo","emoji":"🛫","cost":400},
  {"id":"vehiculo-40","name":"Ascua Vehículo 3","kind":"vehiculo","emoji":"🛩️","cost":400},
  {"id":"vehiculo-41","name":"Forja Vehículo 3","kind":"vehiculo","emoji":"💺","cost":400},
  {"id":"vehiculo-42","name":"Brasa Vehículo 3","kind":"vehiculo","emoji":"🚁","cost":400},
  {"id":"vehiculo-43","name":"Yunque Vehículo 3","kind":"vehiculo","emoji":"🚀","cost":400},
  {"id":"vehiculo-44","name":"Carbón Vehículo 3","kind":"vehiculo","emoji":"🛸","cost":400},
  {"id":"vehiculo-45","name":"Acero Vehículo 3","kind":"vehiculo","emoji":"🛰️","cost":400},
  {"id":"vehiculo-46","name":"Ígneo Vehículo 3","kind":"vehiculo","emoji":"⛵","cost":400},
  {"id":"vehiculo-47","name":"Rúnico Vehículo 3","kind":"vehiculo","emoji":"🚤","cost":400},
  {"id":"vehiculo-48","name":"Místico Vehículo 3","kind":"vehiculo","emoji":"🛥️","cost":400},
  {"id":"vehiculo-49","name":"Solar Vehículo 3","kind":"vehiculo","emoji":"🛳️","cost":400},
  {"id":"vehiculo-50","name":"Lunar Vehículo 3","kind":"vehiculo","emoji":"⛴️","cost":400},
  {"id":"vehiculo-51","name":"Estelar Vehículo 3","kind":"vehiculo","emoji":"🚢","cost":400},
  {"id":"vehiculo-52","name":"Sombrío Vehículo 3","kind":"vehiculo","emoji":"⚓","cost":400},
  {"id":"vehiculo-53","name":"Dorado Vehículo 3","kind":"vehiculo","emoji":"⛽","cost":400},
  {"id":"vehiculo-54","name":"Carmesí Vehículo 3","kind":"vehiculo","emoji":"🚦","cost":400},
  {"id":"vehiculo-55","name":"Ébano Vehículo 3","kind":"vehiculo","emoji":"🚥","cost":400},
  {"id":"vehiculo-56","name":"Cristal Vehículo 3","kind":"vehiculo","emoji":"🗺️","cost":400},
  {"id":"vehiculo-57","name":"Fénix Vehículo 3","kind":"vehiculo","emoji":"🗿","cost":400},
  {"id":"vehiculo-58","name":"Titán Vehículo 3","kind":"vehiculo","emoji":"🗽","cost":400},
  {"id":"vehiculo-59","name":"Obsidiana Vehículo 3","kind":"vehiculo","emoji":"⛲","cost":400},
  {"id":"simbolo-0","name":"Ascua Símbolo","kind":"simbolo","emoji":"❤️","cost":20},
  {"id":"simbolo-1","name":"Forja Símbolo","kind":"simbolo","emoji":"🧡","cost":20},
  {"id":"simbolo-2","name":"Brasa Símbolo","kind":"simbolo","emoji":"💛","cost":20},
  {"id":"simbolo-3","name":"Yunque Símbolo","kind":"simbolo","emoji":"💚","cost":40},
  {"id":"simbolo-4","name":"Carbón Símbolo","kind":"simbolo","emoji":"💙","cost":40},
  {"id":"simbolo-5","name":"Acero Símbolo","kind":"simbolo","emoji":"💜","cost":40},
  {"id":"simbolo-6","name":"Ígneo Símbolo","kind":"simbolo","emoji":"🖤","cost":60},
  {"id":"simbolo-7","name":"Rúnico Símbolo","kind":"simbolo","emoji":"🤍","cost":60},
  {"id":"simbolo-8","name":"Místico Símbolo","kind":"simbolo","emoji":"🤎","cost":60},
  {"id":"simbolo-9","name":"Solar Símbolo","kind":"simbolo","emoji":"💔","cost":90},
  {"id":"simbolo-10","name":"Lunar Símbolo","kind":"simbolo","emoji":"❣️","cost":90},
  {"id":"simbolo-11","name":"Estelar Símbolo","kind":"simbolo","emoji":"💕","cost":90},
  {"id":"simbolo-12","name":"Sombrío Símbolo","kind":"simbolo","emoji":"💞","cost":120},
  {"id":"simbolo-13","name":"Dorado Símbolo","kind":"simbolo","emoji":"💓","cost":120},
  {"id":"simbolo-14","name":"Carmesí Símbolo","kind":"simbolo","emoji":"💗","cost":120},
  {"id":"simbolo-15","name":"Ébano Símbolo","kind":"simbolo","emoji":"💖","cost":160},
  {"id":"simbolo-16","name":"Cristal Símbolo","kind":"simbolo","emoji":"💘","cost":160},
  {"id":"simbolo-17","name":"Fénix Símbolo","kind":"simbolo","emoji":"💝","cost":160},
  {"id":"simbolo-18","name":"Titán Símbolo","kind":"simbolo","emoji":"💟","cost":220},
  {"id":"simbolo-19","name":"Obsidiana Símbolo","kind":"simbolo","emoji":"♈","cost":220},
  {"id":"simbolo-20","name":"Ascua Símbolo 2","kind":"simbolo","emoji":"♉","cost":220},
  {"id":"simbolo-21","name":"Forja Símbolo 2","kind":"simbolo","emoji":"♊","cost":300},
  {"id":"simbolo-22","name":"Brasa Símbolo 2","kind":"simbolo","emoji":"♋","cost":300},
  {"id":"simbolo-23","name":"Yunque Símbolo 2","kind":"simbolo","emoji":"♌","cost":300},
  {"id":"simbolo-24","name":"Carbón Símbolo 2","kind":"simbolo","emoji":"♍","cost":400},
  {"id":"simbolo-25","name":"Acero Símbolo 2","kind":"simbolo","emoji":"♎","cost":400},
  {"id":"simbolo-26","name":"Ígneo Símbolo 2","kind":"simbolo","emoji":"♏","cost":400},
  {"id":"simbolo-27","name":"Rúnico Símbolo 2","kind":"simbolo","emoji":"♐","cost":400},
  {"id":"simbolo-28","name":"Místico Símbolo 2","kind":"simbolo","emoji":"♑","cost":400},
  {"id":"simbolo-29","name":"Solar Símbolo 2","kind":"simbolo","emoji":"♒","cost":400},
  {"id":"simbolo-30","name":"Lunar Símbolo 2","kind":"simbolo","emoji":"♓","cost":400},
  {"id":"simbolo-31","name":"Estelar Símbolo 2","kind":"simbolo","emoji":"♻️","cost":400},
  {"id":"simbolo-32","name":"Sombrío Símbolo 2","kind":"simbolo","emoji":"✅","cost":400},
  {"id":"simbolo-33","name":"Dorado Símbolo 2","kind":"simbolo","emoji":"✴️","cost":400},
  {"id":"simbolo-34","name":"Carmesí Símbolo 2","kind":"simbolo","emoji":"❇️","cost":400},
  {"id":"simbolo-35","name":"Ébano Símbolo 2","kind":"simbolo","emoji":"✳️","cost":400},
  {"id":"simbolo-36","name":"Cristal Símbolo 2","kind":"simbolo","emoji":"❎","cost":400},
  {"id":"simbolo-37","name":"Fénix Símbolo 2","kind":"simbolo","emoji":"🌐","cost":400},
  {"id":"simbolo-38","name":"Titán Símbolo 2","kind":"simbolo","emoji":"💤","cost":400},
]
