import type { StoreItem } from '@/types'

/**
 * Catálogo de la TIENDA (generado). 558 ítems con nombres reales.
 * Fuente única en código; el seed SQL (store_items) se genera del mismo listado.
 * Kinds equipables en Focus Pet: pet, hat, outfit, accessory.
 */
export const EQUIPPABLE_KINDS = ['pet', 'hat', 'outfit', 'accessory'] as const

export const STORE_CATALOG: StoreItem[] = [
  {"id":"gato","name":"Gato","kind":"pet","emoji":"🐱","cost":0},
  {"id":"perro","name":"Perro","kind":"pet","emoji":"🐶","cost":0},
  {"id":"zorro","name":"Zorro","kind":"pet","emoji":"🦊","cost":80},
  {"id":"buho","name":"Búho","kind":"pet","emoji":"🦉","cost":120},
  {"id":"dragon","name":"Dragón","kind":"pet","emoji":"🐉","cost":300},
  {"id":"gorro","name":"Sombrero de copa","kind":"hat","emoji":"🎩","cost":30},
  {"id":"corona","name":"Corona","kind":"hat","emoji":"👑","cost":150},
  {"id":"bufanda","name":"Bufanda","kind":"outfit","emoji":"🧣","cost":40},
  {"id":"capa","name":"Capa de héroe","kind":"outfit","emoji":"🦸","cost":120},
  {"id":"gafas","name":"Gafas de sol","kind":"accessory","emoji":"🕶️","cost":25},
  {"id":"medalla","name":"Medalla","kind":"accessory","emoji":"🏅","cost":60},
  {"id":"pet-0","name":"Conejo","kind":"pet","emoji":"🐰","cost":0},
  {"id":"pet-1","name":"Hámster","kind":"pet","emoji":"🐹","cost":0},
  {"id":"pet-2","name":"Ratón","kind":"pet","emoji":"🐭","cost":20},
  {"id":"pet-3","name":"Oso","kind":"pet","emoji":"🐻","cost":40},
  {"id":"pet-4","name":"Panda","kind":"pet","emoji":"🐼","cost":40},
  {"id":"pet-5","name":"Koala","kind":"pet","emoji":"🐨","cost":40},
  {"id":"pet-6","name":"Tigre","kind":"pet","emoji":"🐯","cost":60},
  {"id":"pet-7","name":"León","kind":"pet","emoji":"🦁","cost":60},
  {"id":"pet-8","name":"Vaca","kind":"pet","emoji":"🐮","cost":60},
  {"id":"pet-9","name":"Cerdito","kind":"pet","emoji":"🐷","cost":90},
  {"id":"pet-10","name":"Rana","kind":"pet","emoji":"🐸","cost":90},
  {"id":"pet-11","name":"Mono","kind":"pet","emoji":"🐵","cost":90},
  {"id":"pet-12","name":"Gallina","kind":"pet","emoji":"🐔","cost":120},
  {"id":"pet-13","name":"Pingüino","kind":"pet","emoji":"🐧","cost":120},
  {"id":"pet-14","name":"Pájaro","kind":"pet","emoji":"🐦","cost":120},
  {"id":"pet-15","name":"Pato","kind":"pet","emoji":"🦆","cost":160},
  {"id":"pet-16","name":"Águila","kind":"pet","emoji":"🦅","cost":160},
  {"id":"pet-17","name":"Murciélago","kind":"pet","emoji":"🦇","cost":160},
  {"id":"pet-18","name":"Lobo","kind":"pet","emoji":"🐺","cost":220},
  {"id":"pet-19","name":"Jabalí","kind":"pet","emoji":"🐗","cost":220},
  {"id":"pet-20","name":"Caballo","kind":"pet","emoji":"🐴","cost":220},
  {"id":"pet-21","name":"Unicornio","kind":"pet","emoji":"🦄","cost":300},
  {"id":"pet-22","name":"Abeja","kind":"pet","emoji":"🐝","cost":300},
  {"id":"pet-23","name":"Mariposa","kind":"pet","emoji":"🦋","cost":300},
  {"id":"pet-24","name":"Caracol","kind":"pet","emoji":"🐌","cost":400},
  {"id":"pet-25","name":"Mariquita","kind":"pet","emoji":"🐞","cost":400},
  {"id":"pet-26","name":"Tortuga","kind":"pet","emoji":"🐢","cost":400},
  {"id":"pet-27","name":"Serpiente","kind":"pet","emoji":"🐍","cost":400},
  {"id":"pet-28","name":"Lagarto","kind":"pet","emoji":"🦎","cost":400},
  {"id":"pet-29","name":"Pulpo","kind":"pet","emoji":"🐙","cost":400},
  {"id":"pet-30","name":"Calamar","kind":"pet","emoji":"🦑","cost":400},
  {"id":"pet-31","name":"Cangrejo","kind":"pet","emoji":"🦀","cost":400},
  {"id":"pet-32","name":"Langosta","kind":"pet","emoji":"🦞","cost":400},
  {"id":"pet-33","name":"Pez tropical","kind":"pet","emoji":"🐠","cost":400},
  {"id":"pet-34","name":"Pececito","kind":"pet","emoji":"🐟","cost":400},
  {"id":"pet-35","name":"Pez globo","kind":"pet","emoji":"🐡","cost":400},
  {"id":"pet-36","name":"Delfín","kind":"pet","emoji":"🐬","cost":400},
  {"id":"pet-37","name":"Ballena","kind":"pet","emoji":"🐳","cost":400},
  {"id":"pet-38","name":"Ballena azul","kind":"pet","emoji":"🐋","cost":400},
  {"id":"pet-39","name":"Tiburón","kind":"pet","emoji":"🦈","cost":400},
  {"id":"pet-40","name":"Leopardo","kind":"pet","emoji":"🐆","cost":400},
  {"id":"pet-41","name":"Tigre de Bengala","kind":"pet","emoji":"🐅","cost":400},
  {"id":"pet-42","name":"Cebra","kind":"pet","emoji":"🦓","cost":400},
  {"id":"pet-43","name":"Gorila","kind":"pet","emoji":"🦍","cost":400},
  {"id":"pet-44","name":"Elefante","kind":"pet","emoji":"🐘","cost":400},
  {"id":"pet-45","name":"Hipopótamo","kind":"pet","emoji":"🦛","cost":400},
  {"id":"pet-46","name":"Rinoceronte","kind":"pet","emoji":"🦏","cost":400},
  {"id":"pet-47","name":"Dromedario","kind":"pet","emoji":"🐪","cost":400},
  {"id":"pet-48","name":"Camello","kind":"pet","emoji":"🐫","cost":400},
  {"id":"pet-49","name":"Jirafa","kind":"pet","emoji":"🦒","cost":400},
  {"id":"pet-50","name":"Canguro","kind":"pet","emoji":"🦘","cost":400},
  {"id":"pet-51","name":"Toro","kind":"pet","emoji":"🐂","cost":400},
  {"id":"pet-52","name":"Vaca lechera","kind":"pet","emoji":"🐄","cost":400},
  {"id":"pet-53","name":"Corcel","kind":"pet","emoji":"🐎","cost":400},
  {"id":"pet-54","name":"Cochinillo","kind":"pet","emoji":"🐖","cost":400},
  {"id":"pet-55","name":"Carnero","kind":"pet","emoji":"🐏","cost":400},
  {"id":"pet-56","name":"Oveja","kind":"pet","emoji":"🐑","cost":400},
  {"id":"pet-57","name":"Llama","kind":"pet","emoji":"🦙","cost":400},
  {"id":"pet-58","name":"Cabra","kind":"pet","emoji":"🐐","cost":400},
  {"id":"pet-59","name":"Ciervo","kind":"pet","emoji":"🦌","cost":400},
  {"id":"pet-60","name":"Caniche","kind":"pet","emoji":"🐩","cost":400},
  {"id":"pet-61","name":"Mapache","kind":"pet","emoji":"🦝","cost":400},
  {"id":"pet-62","name":"Mofeta","kind":"pet","emoji":"🦨","cost":400},
  {"id":"pet-63","name":"Tejón","kind":"pet","emoji":"🦡","cost":400},
  {"id":"pet-64","name":"Nutria","kind":"pet","emoji":"🦦","cost":400},
  {"id":"pet-65","name":"Perezoso","kind":"pet","emoji":"🦥","cost":400},
  {"id":"pet-66","name":"Ardilla","kind":"pet","emoji":"🐿️","cost":400},
  {"id":"pet-67","name":"Erizo","kind":"pet","emoji":"🦔","cost":400},
  {"id":"pet-68","name":"Pavo real","kind":"pet","emoji":"🦚","cost":400},
  {"id":"pet-69","name":"Loro","kind":"pet","emoji":"🦜","cost":400},
  {"id":"pet-70","name":"Cisne","kind":"pet","emoji":"🦢","cost":400},
  {"id":"pet-71","name":"Flamenco","kind":"pet","emoji":"🦩","cost":400},
  {"id":"pet-72","name":"Paloma","kind":"pet","emoji":"🕊️","cost":400},
  {"id":"pet-73","name":"Conejito","kind":"pet","emoji":"🐇","cost":400},
  {"id":"hat-0","name":"Birrete","kind":"hat","emoji":"🎓","cost":20},
  {"id":"hat-1","name":"Casco de rescate","kind":"hat","emoji":"⛑️","cost":20},
  {"id":"hat-2","name":"Casco militar","kind":"hat","emoji":"🪖","cost":20},
  {"id":"hat-3","name":"Gorra","kind":"hat","emoji":"🧢","cost":40},
  {"id":"hat-4","name":"Pamela","kind":"hat","emoji":"👒","cost":40},
  {"id":"hat-5","name":"Calabaza","kind":"hat","emoji":"🎃","cost":40},
  {"id":"hat-6","name":"Antiparras","kind":"hat","emoji":"🥽","cost":60},
  {"id":"hat-7","name":"Lazo","kind":"hat","emoji":"🎀","cost":60},
  {"id":"hat-8","name":"Alien","kind":"hat","emoji":"👽","cost":60},
  {"id":"hat-9","name":"Robot","kind":"hat","emoji":"🤖","cost":90},
  {"id":"hat-10","name":"Cerebro","kind":"hat","emoji":"🧠","cost":90},
  {"id":"hat-11","name":"Flor de cerezo","kind":"hat","emoji":"🌸","cost":90},
  {"id":"hat-12","name":"Hibisco","kind":"hat","emoji":"🌺","cost":120},
  {"id":"hat-13","name":"Girasol","kind":"hat","emoji":"🌻","cost":120},
  {"id":"hat-14","name":"Seta","kind":"hat","emoji":"🍄","cost":120},
  {"id":"hat-15","name":"Estrella","kind":"hat","emoji":"⭐","cost":160},
  {"id":"hat-16","name":"Destellos","kind":"hat","emoji":"✨","cost":160},
  {"id":"hat-17","name":"Estrella fugaz","kind":"hat","emoji":"💫","cost":160},
  {"id":"hat-18","name":"Llama","kind":"hat","emoji":"🔥","cost":220},
  {"id":"hat-19","name":"Copo de nieve","kind":"hat","emoji":"❄️","cost":220},
  {"id":"hat-20","name":"Aureola","kind":"hat","emoji":"😇","cost":220},
  {"id":"hat-21","name":"Querubín","kind":"hat","emoji":"👼","cost":300},
  {"id":"hat-22","name":"Mago","kind":"hat","emoji":"🧙","cost":300},
  {"id":"hat-23","name":"Vampiro","kind":"hat","emoji":"🧛","cost":300},
  {"id":"hat-24","name":"Sirena","kind":"hat","emoji":"🧜","cost":400},
  {"id":"hat-25","name":"Hada","kind":"hat","emoji":"🧚","cost":400},
  {"id":"hat-26","name":"Tengu","kind":"hat","emoji":"👺","cost":400},
  {"id":"hat-27","name":"Ogro","kind":"hat","emoji":"👹","cost":400},
  {"id":"hat-28","name":"Vaquero","kind":"hat","emoji":"🤠","cost":400},
  {"id":"hat-29","name":"Ninja","kind":"hat","emoji":"🥷","cost":400},
  {"id":"hat-30","name":"Papá Noel","kind":"hat","emoji":"🎅","cost":400},
  {"id":"hat-31","name":"Mamá Noel","kind":"hat","emoji":"🤶","cost":400},
  {"id":"outfit-0","name":"Bata","kind":"outfit","emoji":"🥼","cost":20},
  {"id":"outfit-1","name":"Kimono","kind":"outfit","emoji":"🥋","cost":20},
  {"id":"outfit-2","name":"Corbata","kind":"outfit","emoji":"👔","cost":20},
  {"id":"outfit-3","name":"Camiseta","kind":"outfit","emoji":"👕","cost":40},
  {"id":"outfit-4","name":"Vestido","kind":"outfit","emoji":"👗","cost":40},
  {"id":"outfit-5","name":"Kimono floral","kind":"outfit","emoji":"👘","cost":40},
  {"id":"outfit-6","name":"Sari","kind":"outfit","emoji":"🥻","cost":60},
  {"id":"outfit-7","name":"Bañador","kind":"outfit","emoji":"🩱","cost":60},
  {"id":"outfit-8","name":"Bikini","kind":"outfit","emoji":"👙","cost":60},
  {"id":"outfit-9","name":"Blusa","kind":"outfit","emoji":"👚","cost":90},
  {"id":"outfit-10","name":"Abrigo","kind":"outfit","emoji":"🧥","cost":90},
  {"id":"outfit-11","name":"Pantalón corto","kind":"outfit","emoji":"🩳","cost":90},
  {"id":"outfit-12","name":"Vaqueros","kind":"outfit","emoji":"👖","cost":120},
  {"id":"outfit-13","name":"Atletismo","kind":"outfit","emoji":"🎽","cost":120},
  {"id":"outfit-14","name":"Chaleco","kind":"outfit","emoji":"🦺","cost":120},
  {"id":"outfit-15","name":"Calcetines","kind":"outfit","emoji":"🧦","cost":160},
  {"id":"outfit-16","name":"Ropa interior","kind":"outfit","emoji":"🩲","cost":160},
  {"id":"outfit-17","name":"Monedero","kind":"outfit","emoji":"👛","cost":160},
  {"id":"outfit-18","name":"Bolso","kind":"outfit","emoji":"👜","cost":220},
  {"id":"outfit-19","name":"Mochila","kind":"outfit","emoji":"🎒","cost":220},
  {"id":"outfit-20","name":"Guantes","kind":"outfit","emoji":"🧤","cost":220},
  {"id":"outfit-21","name":"Arcoíris","kind":"outfit","emoji":"🌈","cost":300},
  {"id":"outfit-22","name":"Escudo novato","kind":"outfit","emoji":"🔰","cost":300},
  {"id":"outfit-23","name":"Roseta","kind":"outfit","emoji":"🏵️","cost":300},
  {"id":"accessory-0","name":"Gafas","kind":"accessory","emoji":"👓","cost":20},
  {"id":"accessory-1","name":"Oro","kind":"accessory","emoji":"🥇","cost":20},
  {"id":"accessory-2","name":"Plata","kind":"accessory","emoji":"🥈","cost":20},
  {"id":"accessory-3","name":"Bronce","kind":"accessory","emoji":"🥉","cost":40},
  {"id":"accessory-4","name":"Anillo","kind":"accessory","emoji":"💍","cost":40},
  {"id":"accessory-5","name":"Collar","kind":"accessory","emoji":"📿","cost":40},
  {"id":"accessory-6","name":"Diamante","kind":"accessory","emoji":"💎","cost":60},
  {"id":"accessory-7","name":"Bola de cristal","kind":"accessory","emoji":"🔮","cost":60},
  {"id":"accessory-8","name":"Reloj","kind":"accessory","emoji":"⌚","cost":60},
  {"id":"accessory-9","name":"Móvil","kind":"accessory","emoji":"📱","cost":90},
  {"id":"accessory-10","name":"Auriculares","kind":"accessory","emoji":"🎧","cost":90},
  {"id":"accessory-11","name":"Mando","kind":"accessory","emoji":"🎮","cost":90},
  {"id":"accessory-12","name":"Joystick","kind":"accessory","emoji":"🕹️","cost":120},
  {"id":"accessory-13","name":"Dado","kind":"accessory","emoji":"🎲","cost":120},
  {"id":"accessory-14","name":"Comodín","kind":"accessory","emoji":"🃏","cost":120},
  {"id":"accessory-15","name":"Diana","kind":"accessory","emoji":"🎯","cost":160},
  {"id":"accessory-16","name":"Varita mágica","kind":"accessory","emoji":"🪄","cost":160},
  {"id":"accessory-17","name":"Daga","kind":"accessory","emoji":"🗡️","cost":160},
  {"id":"accessory-18","name":"Escudo","kind":"accessory","emoji":"🛡️","cost":220},
  {"id":"accessory-19","name":"Espadas","kind":"accessory","emoji":"⚔️","cost":220},
  {"id":"accessory-20","name":"Arco","kind":"accessory","emoji":"🏹","cost":220},
  {"id":"accessory-21","name":"Tridente","kind":"accessory","emoji":"🔱","cost":300},
  {"id":"accessory-22","name":"Flor de lis","kind":"accessory","emoji":"⚜️","cost":300},
  {"id":"accessory-23","name":"Condecoración","kind":"accessory","emoji":"🎖️","cost":300},
  {"id":"aura-0","name":"Estrella brillante","kind":"aura","emoji":"🌟","cost":20},
  {"id":"aura-1","name":"Explosión","kind":"aura","emoji":"💥","cost":20},
  {"id":"aura-2","name":"Rayo","kind":"aura","emoji":"⚡","cost":20},
  {"id":"aura-3","name":"Ola","kind":"aura","emoji":"🌊","cost":40},
  {"id":"aura-4","name":"Ráfaga","kind":"aura","emoji":"💨","cost":40},
  {"id":"aura-5","name":"Espiral","kind":"aura","emoji":"🌀","cost":40},
  {"id":"aura-6","name":"Tornado","kind":"aura","emoji":"🌪️","cost":60},
  {"id":"aura-7","name":"Burbujas","kind":"aura","emoji":"🫧","cost":60},
  {"id":"aura-8","name":"Gota","kind":"aura","emoji":"💧","cost":60},
  {"id":"aura-9","name":"Gota carmesí","kind":"aura","emoji":"🩸","cost":90},
  {"id":"aura-10","name":"Cometa","kind":"aura","emoji":"☄️","cost":90},
  {"id":"aura-11","name":"Deseo estelar","kind":"aura","emoji":"🌠","cost":90},
  {"id":"aura-12","name":"Fuegos artificiales","kind":"aura","emoji":"🎆","cost":120},
  {"id":"aura-13","name":"Bengala","kind":"aura","emoji":"🎇","cost":120},
  {"id":"aura-14","name":"Vela","kind":"aura","emoji":"🕯️","cost":120},
  {"id":"aura-15","name":"Rombo","kind":"aura","emoji":"💠","cost":160},
  {"id":"aura-16","name":"Brillo intenso","kind":"aura","emoji":"🔆","cost":160},
  {"id":"aura-17","name":"Brillo tenue","kind":"aura","emoji":"🔅","cost":160},
  {"id":"aura-18","name":"Vapor","kind":"aura","emoji":"♨️","cost":220},
  {"id":"fondo-0","name":"Volcán","kind":"fondo","emoji":"🌋","cost":20},
  {"id":"fondo-1","name":"Montaña nevada","kind":"fondo","emoji":"🏔️","cost":20},
  {"id":"fondo-2","name":"Montaña","kind":"fondo","emoji":"⛰️","cost":20},
  {"id":"fondo-3","name":"Vía Láctea","kind":"fondo","emoji":"🌌","cost":40},
  {"id":"fondo-4","name":"Parque natural","kind":"fondo","emoji":"🏞️","cost":40},
  {"id":"fondo-5","name":"Desierto","kind":"fondo","emoji":"🏜️","cost":40},
  {"id":"fondo-6","name":"Atardecer urbano","kind":"fondo","emoji":"🌇","cost":60},
  {"id":"fondo-7","name":"Ciudad al anochecer","kind":"fondo","emoji":"🌆","cost":60},
  {"id":"fondo-8","name":"Skyline","kind":"fondo","emoji":"🏙️","cost":60},
  {"id":"fondo-9","name":"Noche estrellada","kind":"fondo","emoji":"🌃","cost":90},
  {"id":"fondo-10","name":"Puente nocturno","kind":"fondo","emoji":"🌉","cost":90},
  {"id":"fondo-11","name":"Isla","kind":"fondo","emoji":"🏝️","cost":90},
  {"id":"fondo-12","name":"Campamento","kind":"fondo","emoji":"🏕️","cost":120},
  {"id":"fondo-13","name":"Castillo","kind":"fondo","emoji":"🏰","cost":120},
  {"id":"fondo-14","name":"Castillo japonés","kind":"fondo","emoji":"🏯","cost":120},
  {"id":"fondo-15","name":"Torre","kind":"fondo","emoji":"🗼","cost":160},
  {"id":"fondo-16","name":"Amanecer","kind":"fondo","emoji":"🌅","cost":160},
  {"id":"fondo-17","name":"Alba en montaña","kind":"fondo","emoji":"🌄","cost":160},
  {"id":"fondo-18","name":"Niebla","kind":"fondo","emoji":"🌁","cost":220},
  {"id":"fondo-19","name":"Planeta","kind":"fondo","emoji":"🪐","cost":220},
  {"id":"fondo-20","name":"Planeta Tierra","kind":"fondo","emoji":"🌏","cost":220},
  {"id":"fondo-21","name":"Luna","kind":"fondo","emoji":"🌙","cost":300},
  {"id":"insignia-0","name":"Trofeo","kind":"insignia","emoji":"🏆","cost":20},
  {"id":"insignia-1","name":"Cien puntos","kind":"insignia","emoji":"💯","cost":20},
  {"id":"insignia-2","name":"Lazo conmemorativo","kind":"insignia","emoji":"🎗️","cost":20},
  {"id":"insignia-3","name":"Picas","kind":"insignia","emoji":"♠️","cost":40},
  {"id":"insignia-4","name":"Corazones","kind":"insignia","emoji":"♥️","cost":40},
  {"id":"insignia-5","name":"Diamantes","kind":"insignia","emoji":"♦️","cost":40},
  {"id":"insignia-6","name":"Tréboles","kind":"insignia","emoji":"♣️","cost":60},
  {"id":"insignia-7","name":"Dragón rojo","kind":"insignia","emoji":"🀄","cost":60},
  {"id":"insignia-8","name":"Yin y yang","kind":"insignia","emoji":"☯️","cost":60},
  {"id":"insignia-9","name":"Om","kind":"insignia","emoji":"🕉️","cost":90},
  {"id":"insignia-10","name":"Cruz","kind":"insignia","emoji":"✝️","cost":90},
  {"id":"insignia-11","name":"Media luna","kind":"insignia","emoji":"☪️","cost":90},
  {"id":"insignia-12","name":"Estrella de seis puntas","kind":"insignia","emoji":"🔯","cost":120},
  {"id":"insignia-13","name":"Lugar de culto","kind":"insignia","emoji":"🛐","cost":120},
  {"id":"insignia-14","name":"Átomo","kind":"insignia","emoji":"⚛️","cost":120},
  {"id":"comida-0","name":"Manzana","kind":"comida","emoji":"🍎","cost":20},
  {"id":"comida-1","name":"Pizza","kind":"comida","emoji":"🍕","cost":20},
  {"id":"comida-2","name":"Hamburguesa","kind":"comida","emoji":"🍔","cost":20},
  {"id":"comida-3","name":"Papas fritas","kind":"comida","emoji":"🍟","cost":40},
  {"id":"comida-4","name":"Perrito caliente","kind":"comida","emoji":"🌭","cost":40},
  {"id":"comida-5","name":"Palomitas","kind":"comida","emoji":"🍿","cost":40},
  {"id":"comida-6","name":"Sal","kind":"comida","emoji":"🧂","cost":60},
  {"id":"comida-7","name":"Tocino","kind":"comida","emoji":"🥓","cost":60},
  {"id":"comida-8","name":"Panqueques","kind":"comida","emoji":"🥞","cost":60},
  {"id":"comida-9","name":"Gofre","kind":"comida","emoji":"🧇","cost":90},
  {"id":"comida-10","name":"Huevo frito","kind":"comida","emoji":"🍳","cost":90},
  {"id":"comida-11","name":"Huevo","kind":"comida","emoji":"🥚","cost":90},
  {"id":"comida-12","name":"Queso","kind":"comida","emoji":"🧀","cost":120},
  {"id":"comida-13","name":"Pretzel","kind":"comida","emoji":"🥨","cost":120},
  {"id":"comida-14","name":"Cruasán","kind":"comida","emoji":"🥐","cost":120},
  {"id":"comida-15","name":"Baguette","kind":"comida","emoji":"🥖","cost":160},
  {"id":"comida-16","name":"Pan","kind":"comida","emoji":"🍞","cost":160},
  {"id":"comida-17","name":"Rosca","kind":"comida","emoji":"🥯","cost":160},
  {"id":"comida-18","name":"Ramen","kind":"comida","emoji":"🍜","cost":220},
  {"id":"comida-19","name":"Guiso","kind":"comida","emoji":"🍲","cost":220},
  {"id":"comida-20","name":"Curry","kind":"comida","emoji":"🍛","cost":220},
  {"id":"comida-21","name":"Langostino","kind":"comida","emoji":"🍤","cost":300},
  {"id":"comida-22","name":"Onigiri","kind":"comida","emoji":"🍙","cost":300},
  {"id":"comida-23","name":"Arroz","kind":"comida","emoji":"🍚","cost":300},
  {"id":"comida-24","name":"Galleta de arroz","kind":"comida","emoji":"🍘","cost":400},
  {"id":"comida-25","name":"Oden","kind":"comida","emoji":"🍢","cost":400},
  {"id":"comida-26","name":"Dango","kind":"comida","emoji":"🍡","cost":400},
  {"id":"comida-27","name":"Raspado","kind":"comida","emoji":"🍧","cost":400},
  {"id":"comida-28","name":"Helado","kind":"comida","emoji":"🍨","cost":400},
  {"id":"comida-29","name":"Cucurucho","kind":"comida","emoji":"🍦","cost":400},
  {"id":"comida-30","name":"Tarta","kind":"comida","emoji":"🥧","cost":400},
  {"id":"comida-31","name":"Magdalena","kind":"comida","emoji":"🧁","cost":400},
  {"id":"comida-32","name":"Pastel","kind":"comida","emoji":"🍰","cost":400},
  {"id":"comida-33","name":"Tarta de cumpleaños","kind":"comida","emoji":"🎂","cost":400},
  {"id":"comida-34","name":"Flan","kind":"comida","emoji":"🍮","cost":400},
  {"id":"comida-35","name":"Piruleta","kind":"comida","emoji":"🍭","cost":400},
  {"id":"comida-36","name":"Caramelo","kind":"comida","emoji":"🍬","cost":400},
  {"id":"comida-37","name":"Chocolate","kind":"comida","emoji":"🍫","cost":400},
  {"id":"comida-38","name":"Dona","kind":"comida","emoji":"🍩","cost":400},
  {"id":"comida-39","name":"Galleta","kind":"comida","emoji":"🍪","cost":400},
  {"id":"comida-40","name":"Castaña","kind":"comida","emoji":"🌰","cost":400},
  {"id":"comida-41","name":"Cacahuete","kind":"comida","emoji":"🥜","cost":400},
  {"id":"comida-42","name":"Miel","kind":"comida","emoji":"🍯","cost":400},
  {"id":"comida-43","name":"Leche","kind":"comida","emoji":"🥛","cost":400},
  {"id":"comida-44","name":"Café","kind":"comida","emoji":"☕","cost":400},
  {"id":"comida-45","name":"Té","kind":"comida","emoji":"🍵","cost":400},
  {"id":"comida-46","name":"Zumo","kind":"comida","emoji":"🧃","cost":400},
  {"id":"comida-47","name":"Refresco","kind":"comida","emoji":"🥤","cost":400},
  {"id":"comida-48","name":"Té de burbujas","kind":"comida","emoji":"🧋","cost":400},
  {"id":"comida-49","name":"Cerveza","kind":"comida","emoji":"🍺","cost":400},
  {"id":"comida-50","name":"Vino","kind":"comida","emoji":"🍷","cost":400},
  {"id":"comida-51","name":"Brindis","kind":"comida","emoji":"🥂","cost":400},
  {"id":"comida-52","name":"Cóctel","kind":"comida","emoji":"🍸","cost":400},
  {"id":"comida-53","name":"Tropical","kind":"comida","emoji":"🍹","cost":400},
  {"id":"comida-54","name":"Taco","kind":"comida","emoji":"🌮","cost":400},
  {"id":"comida-55","name":"Burrito","kind":"comida","emoji":"🌯","cost":400},
  {"id":"comida-56","name":"Tamal","kind":"comida","emoji":"🫔","cost":400},
  {"id":"comida-57","name":"Pita","kind":"comida","emoji":"🥙","cost":400},
  {"id":"comida-58","name":"Falafel","kind":"comida","emoji":"🧆","cost":400},
  {"id":"comida-59","name":"Sushi","kind":"comida","emoji":"🍣","cost":400},
  {"id":"comida-60","name":"Bento","kind":"comida","emoji":"🍱","cost":400},
  {"id":"comida-61","name":"Uvas","kind":"comida","emoji":"🍇","cost":400},
  {"id":"comida-62","name":"Melón","kind":"comida","emoji":"🍈","cost":400},
  {"id":"comida-63","name":"Sandía","kind":"comida","emoji":"🍉","cost":400},
  {"id":"comida-64","name":"Naranja","kind":"comida","emoji":"🍊","cost":400},
  {"id":"comida-65","name":"Limón","kind":"comida","emoji":"🍋","cost":400},
  {"id":"comida-66","name":"Plátano","kind":"comida","emoji":"🍌","cost":400},
  {"id":"comida-67","name":"Piña","kind":"comida","emoji":"🍍","cost":400},
  {"id":"comida-68","name":"Mango","kind":"comida","emoji":"🥭","cost":400},
  {"id":"comida-69","name":"Pera","kind":"comida","emoji":"🍐","cost":400},
  {"id":"comida-70","name":"Melocotón","kind":"comida","emoji":"🍑","cost":400},
  {"id":"comida-71","name":"Cerezas","kind":"comida","emoji":"🍒","cost":400},
  {"id":"comida-72","name":"Fresa","kind":"comida","emoji":"🍓","cost":400},
  {"id":"comida-73","name":"Arándanos","kind":"comida","emoji":"🫐","cost":400},
  {"id":"comida-74","name":"Kiwi","kind":"comida","emoji":"🥝","cost":400},
  {"id":"comida-75","name":"Tomate","kind":"comida","emoji":"🍅","cost":400},
  {"id":"comida-76","name":"Aceituna","kind":"comida","emoji":"🫒","cost":400},
  {"id":"comida-77","name":"Coco","kind":"comida","emoji":"🥥","cost":400},
  {"id":"comida-78","name":"Aguacate","kind":"comida","emoji":"🥑","cost":400},
  {"id":"comida-79","name":"Berenjena","kind":"comida","emoji":"🍆","cost":400},
  {"id":"comida-80","name":"Patata","kind":"comida","emoji":"🥔","cost":400},
  {"id":"comida-81","name":"Zanahoria","kind":"comida","emoji":"🥕","cost":400},
  {"id":"comida-82","name":"Maíz","kind":"comida","emoji":"🌽","cost":400},
  {"id":"comida-83","name":"Chile","kind":"comida","emoji":"🌶️","cost":400},
  {"id":"comida-84","name":"Pimiento","kind":"comida","emoji":"🫑","cost":400},
  {"id":"comida-85","name":"Pepino","kind":"comida","emoji":"🥒","cost":400},
  {"id":"comida-86","name":"Lechuga","kind":"comida","emoji":"🥬","cost":400},
  {"id":"comida-87","name":"Brócoli","kind":"comida","emoji":"🥦","cost":400},
  {"id":"comida-88","name":"Ajo","kind":"comida","emoji":"🧄","cost":400},
  {"id":"comida-89","name":"Cebolla","kind":"comida","emoji":"🧅","cost":400},
  {"id":"planta-0","name":"Brote","kind":"planta","emoji":"🌱","cost":20},
  {"id":"planta-1","name":"Hierba","kind":"planta","emoji":"🌿","cost":20},
  {"id":"planta-2","name":"Trébol","kind":"planta","emoji":"🍀","cost":20},
  {"id":"planta-3","name":"Espiga","kind":"planta","emoji":"🌾","cost":40},
  {"id":"planta-4","name":"Cactus","kind":"planta","emoji":"🌵","cost":40},
  {"id":"planta-5","name":"Palmera","kind":"planta","emoji":"🌴","cost":40},
  {"id":"planta-6","name":"Pino","kind":"planta","emoji":"🌲","cost":60},
  {"id":"planta-7","name":"Árbol","kind":"planta","emoji":"🌳","cost":60},
  {"id":"planta-8","name":"Tanabata","kind":"planta","emoji":"🎋","cost":60},
  {"id":"planta-9","name":"Bambú","kind":"planta","emoji":"🎍","cost":90},
  {"id":"planta-10","name":"Hoja de arce","kind":"planta","emoji":"🍁","cost":90},
  {"id":"planta-11","name":"Hojas secas","kind":"planta","emoji":"🍂","cost":90},
  {"id":"planta-12","name":"Hojas al viento","kind":"planta","emoji":"🍃","cost":120},
  {"id":"planta-13","name":"Tulipán","kind":"planta","emoji":"🌷","cost":120},
  {"id":"planta-14","name":"Rosa","kind":"planta","emoji":"🌹","cost":120},
  {"id":"planta-15","name":"Rosa marchita","kind":"planta","emoji":"🥀","cost":160},
  {"id":"planta-16","name":"Margarita","kind":"planta","emoji":"🌼","cost":160},
  {"id":"planta-17","name":"Ramo","kind":"planta","emoji":"💐","cost":160},
  {"id":"planta-18","name":"Maceta","kind":"planta","emoji":"🪴","cost":220},
  {"id":"deporte-0","name":"Fútbol","kind":"deporte","emoji":"⚽","cost":20},
  {"id":"deporte-1","name":"Baloncesto","kind":"deporte","emoji":"🏀","cost":20},
  {"id":"deporte-2","name":"Fútbol americano","kind":"deporte","emoji":"🏈","cost":20},
  {"id":"deporte-3","name":"Béisbol","kind":"deporte","emoji":"⚾","cost":40},
  {"id":"deporte-4","name":"Softbol","kind":"deporte","emoji":"🥎","cost":40},
  {"id":"deporte-5","name":"Tenis","kind":"deporte","emoji":"🎾","cost":40},
  {"id":"deporte-6","name":"Voleibol","kind":"deporte","emoji":"🏐","cost":60},
  {"id":"deporte-7","name":"Rugby","kind":"deporte","emoji":"🏉","cost":60},
  {"id":"deporte-8","name":"Disco volador","kind":"deporte","emoji":"🥏","cost":60},
  {"id":"deporte-9","name":"Billar","kind":"deporte","emoji":"🎱","cost":90},
  {"id":"deporte-10","name":"Yoyó","kind":"deporte","emoji":"🪀","cost":90},
  {"id":"deporte-11","name":"Ping-pong","kind":"deporte","emoji":"🏓","cost":90},
  {"id":"deporte-12","name":"Bádminton","kind":"deporte","emoji":"🏸","cost":120},
  {"id":"deporte-13","name":"Portería","kind":"deporte","emoji":"🥅","cost":120},
  {"id":"deporte-14","name":"Hockey","kind":"deporte","emoji":"🏒","cost":120},
  {"id":"deporte-15","name":"Hockey hierba","kind":"deporte","emoji":"🏑","cost":160},
  {"id":"deporte-16","name":"Lacrosse","kind":"deporte","emoji":"🥍","cost":160},
  {"id":"deporte-17","name":"Críquet","kind":"deporte","emoji":"🏏","cost":160},
  {"id":"deporte-18","name":"Bumerán","kind":"deporte","emoji":"🪃","cost":220},
  {"id":"deporte-19","name":"Boxeo","kind":"deporte","emoji":"🥊","cost":220},
  {"id":"deporte-20","name":"Monopatín","kind":"deporte","emoji":"🛹","cost":220},
  {"id":"deporte-21","name":"Patines","kind":"deporte","emoji":"🛼","cost":300},
  {"id":"deporte-22","name":"Trineo","kind":"deporte","emoji":"🛷","cost":300},
  {"id":"deporte-23","name":"Patinaje","kind":"deporte","emoji":"⛸️","cost":300},
  {"id":"deporte-24","name":"Curling","kind":"deporte","emoji":"🥌","cost":400},
  {"id":"deporte-25","name":"Esquí","kind":"deporte","emoji":"🎿","cost":400},
  {"id":"deporte-26","name":"Esquiador","kind":"deporte","emoji":"⛷️","cost":400},
  {"id":"deporte-27","name":"Snowboard","kind":"deporte","emoji":"🏂","cost":400},
  {"id":"deporte-28","name":"Pesas","kind":"deporte","emoji":"🏋️","cost":400},
  {"id":"deporte-29","name":"Lucha","kind":"deporte","emoji":"🤼","cost":400},
  {"id":"deporte-30","name":"Gimnasia","kind":"deporte","emoji":"🤸","cost":400},
  {"id":"deporte-31","name":"Esgrima","kind":"deporte","emoji":"🤺","cost":400},
  {"id":"deporte-32","name":"Balonmano","kind":"deporte","emoji":"🤾","cost":400},
  {"id":"deporte-33","name":"Golf","kind":"deporte","emoji":"🏌️","cost":400},
  {"id":"deporte-34","name":"Hípica","kind":"deporte","emoji":"🏇","cost":400},
  {"id":"deporte-35","name":"Yoga","kind":"deporte","emoji":"🧘","cost":400},
  {"id":"deporte-36","name":"Surf","kind":"deporte","emoji":"🏄","cost":400},
  {"id":"deporte-37","name":"Natación","kind":"deporte","emoji":"🏊","cost":400},
  {"id":"deporte-38","name":"Waterpolo","kind":"deporte","emoji":"🤽","cost":400},
  {"id":"deporte-39","name":"Remo","kind":"deporte","emoji":"🚣","cost":400},
  {"id":"deporte-40","name":"Escalada","kind":"deporte","emoji":"🧗","cost":400},
  {"id":"deporte-41","name":"Ciclismo de montaña","kind":"deporte","emoji":"🚵","cost":400},
  {"id":"deporte-42","name":"Ciclismo","kind":"deporte","emoji":"🚴","cost":400},
  {"id":"musica-0","name":"Nota musical","kind":"musica","emoji":"🎵","cost":20},
  {"id":"musica-1","name":"Melodía","kind":"musica","emoji":"🎶","cost":20},
  {"id":"musica-2","name":"Partitura","kind":"musica","emoji":"🎼","cost":20},
  {"id":"musica-3","name":"Micrófono","kind":"musica","emoji":"🎤","cost":40},
  {"id":"musica-4","name":"Saxofón","kind":"musica","emoji":"🎷","cost":40},
  {"id":"musica-5","name":"Guitarra","kind":"musica","emoji":"🎸","cost":40},
  {"id":"musica-6","name":"Piano","kind":"musica","emoji":"🎹","cost":60},
  {"id":"musica-7","name":"Trompeta","kind":"musica","emoji":"🎺","cost":60},
  {"id":"musica-8","name":"Violín","kind":"musica","emoji":"🎻","cost":60},
  {"id":"musica-9","name":"Banjo","kind":"musica","emoji":"🪕","cost":90},
  {"id":"musica-10","name":"Batería","kind":"musica","emoji":"🥁","cost":90},
  {"id":"musica-11","name":"Tambor","kind":"musica","emoji":"🪘","cost":90},
  {"id":"musica-12","name":"Corneta","kind":"musica","emoji":"📯","cost":120},
  {"id":"musica-13","name":"Micrófono de estudio","kind":"musica","emoji":"🎙️","cost":120},
  {"id":"musica-14","name":"Ecualizador","kind":"musica","emoji":"🎚️","cost":120},
  {"id":"musica-15","name":"Mesa de mezclas","kind":"musica","emoji":"🎛️","cost":160},
  {"id":"objeto-0","name":"Bombilla","kind":"objeto","emoji":"💡","cost":20},
  {"id":"objeto-1","name":"Linterna","kind":"objeto","emoji":"🔦","cost":20},
  {"id":"objeto-2","name":"Lámpara de aceite","kind":"objeto","emoji":"🪔","cost":20},
  {"id":"objeto-3","name":"Llave inglesa","kind":"objeto","emoji":"🔧","cost":40},
  {"id":"objeto-4","name":"Martillo","kind":"objeto","emoji":"🔨","cost":40},
  {"id":"objeto-5","name":"Martillo y pico","kind":"objeto","emoji":"⚒️","cost":40},
  {"id":"objeto-6","name":"Herramientas","kind":"objeto","emoji":"🛠️","cost":60},
  {"id":"objeto-7","name":"Pico","kind":"objeto","emoji":"⛏️","cost":60},
  {"id":"objeto-8","name":"Tornillo","kind":"objeto","emoji":"🔩","cost":60},
  {"id":"objeto-9","name":"Engranaje","kind":"objeto","emoji":"⚙️","cost":90},
  {"id":"objeto-10","name":"Caja de herramientas","kind":"objeto","emoji":"🧰","cost":90},
  {"id":"objeto-11","name":"Imán","kind":"objeto","emoji":"🧲","cost":90},
  {"id":"objeto-12","name":"Pistola de agua","kind":"objeto","emoji":"🔫","cost":120},
  {"id":"objeto-13","name":"Bomba","kind":"objeto","emoji":"💣","cost":120},
  {"id":"objeto-14","name":"Petardo","kind":"objeto","emoji":"🧨","cost":120},
  {"id":"objeto-15","name":"Hacha","kind":"objeto","emoji":"🪓","cost":160},
  {"id":"objeto-16","name":"Cuchillo","kind":"objeto","emoji":"🔪","cost":160},
  {"id":"objeto-17","name":"Humo","kind":"objeto","emoji":"🚬","cost":160},
  {"id":"objeto-18","name":"Ataúd","kind":"objeto","emoji":"⚰️","cost":220},
  {"id":"objeto-19","name":"Urna","kind":"objeto","emoji":"⚱️","cost":220},
  {"id":"objeto-20","name":"Ánfora","kind":"objeto","emoji":"🏺","cost":220},
  {"id":"objeto-21","name":"Ojo turco","kind":"objeto","emoji":"🧿","cost":300},
  {"id":"objeto-22","name":"Barbería","kind":"objeto","emoji":"💈","cost":300},
  {"id":"objeto-23","name":"Alambique","kind":"objeto","emoji":"⚗️","cost":300},
  {"id":"objeto-24","name":"Telescopio","kind":"objeto","emoji":"🔭","cost":400},
  {"id":"objeto-25","name":"Microscopio","kind":"objeto","emoji":"🔬","cost":400},
  {"id":"objeto-26","name":"Agujero","kind":"objeto","emoji":"🕳️","cost":400},
  {"id":"objeto-27","name":"Pastilla","kind":"objeto","emoji":"💊","cost":400},
  {"id":"objeto-28","name":"Jeringa","kind":"objeto","emoji":"💉","cost":400},
  {"id":"objeto-29","name":"ADN","kind":"objeto","emoji":"🧬","cost":400},
  {"id":"objeto-30","name":"Microbio","kind":"objeto","emoji":"🦠","cost":400},
  {"id":"objeto-31","name":"Placa Petri","kind":"objeto","emoji":"🧫","cost":400},
  {"id":"objeto-32","name":"Probeta","kind":"objeto","emoji":"🧪","cost":400},
  {"id":"objeto-33","name":"Termómetro","kind":"objeto","emoji":"🌡️","cost":400},
  {"id":"objeto-34","name":"Escoba","kind":"objeto","emoji":"🧹","cost":400},
  {"id":"objeto-35","name":"Cesta","kind":"objeto","emoji":"🧺","cost":400},
  {"id":"objeto-36","name":"Papel","kind":"objeto","emoji":"🧻","cost":400},
  {"id":"objeto-37","name":"Campanilla","kind":"objeto","emoji":"🛎️","cost":400},
  {"id":"objeto-38","name":"Llave","kind":"objeto","emoji":"🔑","cost":400},
  {"id":"objeto-39","name":"Llave antigua","kind":"objeto","emoji":"🗝️","cost":400},
  {"id":"objeto-40","name":"Puerta","kind":"objeto","emoji":"🚪","cost":400},
  {"id":"objeto-41","name":"Silla","kind":"objeto","emoji":"🪑","cost":400},
  {"id":"objeto-42","name":"Sofá","kind":"objeto","emoji":"🛋️","cost":400},
  {"id":"objeto-43","name":"Cama","kind":"objeto","emoji":"🛏️","cost":400},
  {"id":"objeto-44","name":"Osito de peluche","kind":"objeto","emoji":"🧸","cost":400},
  {"id":"objeto-45","name":"Cuadro","kind":"objeto","emoji":"🖼️","cost":400},
  {"id":"objeto-46","name":"Espejo","kind":"objeto","emoji":"🪞","cost":400},
  {"id":"objeto-47","name":"Bolsas","kind":"objeto","emoji":"🛍️","cost":400},
  {"id":"objeto-48","name":"Carrito","kind":"objeto","emoji":"🛒","cost":400},
  {"id":"objeto-49","name":"Regalo","kind":"objeto","emoji":"🎁","cost":400},
  {"id":"objeto-50","name":"Globo","kind":"objeto","emoji":"🎈","cost":400},
  {"id":"objeto-51","name":"Banderines koi","kind":"objeto","emoji":"🎏","cost":400},
  {"id":"objeto-52","name":"Confeti","kind":"objeto","emoji":"🎊","cost":400},
  {"id":"objeto-53","name":"Fiesta","kind":"objeto","emoji":"🎉","cost":400},
  {"id":"objeto-54","name":"Piñata","kind":"objeto","emoji":"🪅","cost":400},
  {"id":"objeto-55","name":"Matrioska","kind":"objeto","emoji":"🪆","cost":400},
  {"id":"objeto-56","name":"Cámara","kind":"objeto","emoji":"📷","cost":400},
  {"id":"objeto-57","name":"Cámara con flash","kind":"objeto","emoji":"📸","cost":400},
  {"id":"objeto-58","name":"Videocámara","kind":"objeto","emoji":"📹","cost":400},
  {"id":"objeto-59","name":"Cinta","kind":"objeto","emoji":"📼","cost":400},
  {"id":"objeto-60","name":"Disquete","kind":"objeto","emoji":"💾","cost":400},
  {"id":"objeto-61","name":"CD","kind":"objeto","emoji":"💿","cost":400},
  {"id":"objeto-62","name":"DVD","kind":"objeto","emoji":"📀","cost":400},
  {"id":"objeto-63","name":"Ábaco","kind":"objeto","emoji":"🧮","cost":400},
  {"id":"objeto-64","name":"Libro rojo","kind":"objeto","emoji":"📕","cost":400},
  {"id":"objeto-65","name":"Libro verde","kind":"objeto","emoji":"📗","cost":400},
  {"id":"objeto-66","name":"Libro azul","kind":"objeto","emoji":"📘","cost":400},
  {"id":"objeto-67","name":"Libro naranja","kind":"objeto","emoji":"📙","cost":400},
  {"id":"objeto-68","name":"Libros","kind":"objeto","emoji":"📚","cost":400},
  {"id":"objeto-69","name":"Libro abierto","kind":"objeto","emoji":"📖","cost":400},
  {"id":"vehiculo-0","name":"Coche","kind":"vehiculo","emoji":"🚗","cost":20},
  {"id":"vehiculo-1","name":"Taxi","kind":"vehiculo","emoji":"🚕","cost":20},
  {"id":"vehiculo-2","name":"Todoterreno","kind":"vehiculo","emoji":"🚙","cost":20},
  {"id":"vehiculo-3","name":"Autobús","kind":"vehiculo","emoji":"🚌","cost":40},
  {"id":"vehiculo-4","name":"Trolebús","kind":"vehiculo","emoji":"🚎","cost":40},
  {"id":"vehiculo-5","name":"Bólido","kind":"vehiculo","emoji":"🏎️","cost":40},
  {"id":"vehiculo-6","name":"Coche de policía","kind":"vehiculo","emoji":"🚓","cost":60},
  {"id":"vehiculo-7","name":"Ambulancia","kind":"vehiculo","emoji":"🚑","cost":60},
  {"id":"vehiculo-8","name":"Camión de bomberos","kind":"vehiculo","emoji":"🚒","cost":60},
  {"id":"vehiculo-9","name":"Furgoneta","kind":"vehiculo","emoji":"🚐","cost":90},
  {"id":"vehiculo-10","name":"Camión","kind":"vehiculo","emoji":"🚚","cost":90},
  {"id":"vehiculo-11","name":"Tráiler","kind":"vehiculo","emoji":"🚛","cost":90},
  {"id":"vehiculo-12","name":"Tractor","kind":"vehiculo","emoji":"🚜","cost":120},
  {"id":"vehiculo-13","name":"Pickup","kind":"vehiculo","emoji":"🛻","cost":120},
  {"id":"vehiculo-14","name":"Moto","kind":"vehiculo","emoji":"🏍️","cost":120},
  {"id":"vehiculo-15","name":"Scooter","kind":"vehiculo","emoji":"🛵","cost":160},
  {"id":"vehiculo-16","name":"Bicicleta","kind":"vehiculo","emoji":"🚲","cost":160},
  {"id":"vehiculo-17","name":"Patinete","kind":"vehiculo","emoji":"🛴","cost":160},
  {"id":"vehiculo-18","name":"Sirena","kind":"vehiculo","emoji":"🚨","cost":220},
  {"id":"vehiculo-19","name":"Patrulla","kind":"vehiculo","emoji":"🚔","cost":220},
  {"id":"vehiculo-20","name":"Autobús que llega","kind":"vehiculo","emoji":"🚍","cost":220},
  {"id":"vehiculo-21","name":"Coche que llega","kind":"vehiculo","emoji":"🚘","cost":300},
  {"id":"vehiculo-22","name":"Taxi que llega","kind":"vehiculo","emoji":"🚖","cost":300},
  {"id":"vehiculo-23","name":"Teleférico","kind":"vehiculo","emoji":"🚡","cost":300},
  {"id":"vehiculo-24","name":"Funicular","kind":"vehiculo","emoji":"🚠","cost":400},
  {"id":"vehiculo-25","name":"Monorraíl suspendido","kind":"vehiculo","emoji":"🚟","cost":400},
  {"id":"vehiculo-26","name":"Vagón","kind":"vehiculo","emoji":"🚃","cost":400},
  {"id":"vehiculo-27","name":"Tranvía","kind":"vehiculo","emoji":"🚋","cost":400},
  {"id":"vehiculo-28","name":"Tren de montaña","kind":"vehiculo","emoji":"🚞","cost":400},
  {"id":"vehiculo-29","name":"Monorraíl","kind":"vehiculo","emoji":"🚝","cost":400},
  {"id":"vehiculo-30","name":"Tren bala","kind":"vehiculo","emoji":"🚄","cost":400},
  {"id":"vehiculo-31","name":"AVE","kind":"vehiculo","emoji":"🚅","cost":400},
  {"id":"vehiculo-32","name":"Tren ligero","kind":"vehiculo","emoji":"🚈","cost":400},
  {"id":"vehiculo-33","name":"Locomotora","kind":"vehiculo","emoji":"🚂","cost":400},
  {"id":"vehiculo-34","name":"Tren","kind":"vehiculo","emoji":"🚆","cost":400},
  {"id":"vehiculo-35","name":"Metro","kind":"vehiculo","emoji":"🚇","cost":400},
  {"id":"vehiculo-36","name":"Tranvía moderno","kind":"vehiculo","emoji":"🚊","cost":400},
  {"id":"vehiculo-37","name":"Estación","kind":"vehiculo","emoji":"🚉","cost":400},
  {"id":"vehiculo-38","name":"Avión","kind":"vehiculo","emoji":"✈️","cost":400},
  {"id":"vehiculo-39","name":"Despegue","kind":"vehiculo","emoji":"🛫","cost":400},
  {"id":"vehiculo-40","name":"Avioneta","kind":"vehiculo","emoji":"🛩️","cost":400},
  {"id":"vehiculo-41","name":"Asiento","kind":"vehiculo","emoji":"💺","cost":400},
  {"id":"vehiculo-42","name":"Helicóptero","kind":"vehiculo","emoji":"🚁","cost":400},
  {"id":"vehiculo-43","name":"Cohete","kind":"vehiculo","emoji":"🚀","cost":400},
  {"id":"vehiculo-44","name":"Platillo volante","kind":"vehiculo","emoji":"🛸","cost":400},
  {"id":"vehiculo-45","name":"Satélite","kind":"vehiculo","emoji":"🛰️","cost":400},
  {"id":"vehiculo-46","name":"Velero","kind":"vehiculo","emoji":"⛵","cost":400},
  {"id":"vehiculo-47","name":"Lancha","kind":"vehiculo","emoji":"🚤","cost":400},
  {"id":"vehiculo-48","name":"Yate","kind":"vehiculo","emoji":"🛥️","cost":400},
  {"id":"vehiculo-49","name":"Crucero","kind":"vehiculo","emoji":"🛳️","cost":400},
  {"id":"vehiculo-50","name":"Ferry","kind":"vehiculo","emoji":"⛴️","cost":400},
  {"id":"vehiculo-51","name":"Barco","kind":"vehiculo","emoji":"🚢","cost":400},
  {"id":"vehiculo-52","name":"Ancla","kind":"vehiculo","emoji":"⚓","cost":400},
  {"id":"vehiculo-53","name":"Gasolinera","kind":"vehiculo","emoji":"⛽","cost":400},
  {"id":"vehiculo-54","name":"Semáforo","kind":"vehiculo","emoji":"🚦","cost":400},
  {"id":"vehiculo-55","name":"Semáforo horizontal","kind":"vehiculo","emoji":"🚥","cost":400},
  {"id":"vehiculo-56","name":"Mapa","kind":"vehiculo","emoji":"🗺️","cost":400},
  {"id":"vehiculo-57","name":"Moái","kind":"vehiculo","emoji":"🗿","cost":400},
  {"id":"vehiculo-58","name":"Estatua de la Libertad","kind":"vehiculo","emoji":"🗽","cost":400},
  {"id":"vehiculo-59","name":"Fuente","kind":"vehiculo","emoji":"⛲","cost":400},
  {"id":"simbolo-0","name":"Corazón rojo","kind":"simbolo","emoji":"❤️","cost":20},
  {"id":"simbolo-1","name":"Corazón naranja","kind":"simbolo","emoji":"🧡","cost":20},
  {"id":"simbolo-2","name":"Corazón amarillo","kind":"simbolo","emoji":"💛","cost":20},
  {"id":"simbolo-3","name":"Corazón verde","kind":"simbolo","emoji":"💚","cost":40},
  {"id":"simbolo-4","name":"Corazón azul","kind":"simbolo","emoji":"💙","cost":40},
  {"id":"simbolo-5","name":"Corazón morado","kind":"simbolo","emoji":"💜","cost":40},
  {"id":"simbolo-6","name":"Corazón negro","kind":"simbolo","emoji":"🖤","cost":60},
  {"id":"simbolo-7","name":"Corazón blanco","kind":"simbolo","emoji":"🤍","cost":60},
  {"id":"simbolo-8","name":"Corazón marrón","kind":"simbolo","emoji":"🤎","cost":60},
  {"id":"simbolo-9","name":"Corazón roto","kind":"simbolo","emoji":"💔","cost":90},
  {"id":"simbolo-10","name":"Corazón exclamación","kind":"simbolo","emoji":"❣️","cost":90},
  {"id":"simbolo-11","name":"Dos corazones","kind":"simbolo","emoji":"💕","cost":90},
  {"id":"simbolo-12","name":"Corazones giratorios","kind":"simbolo","emoji":"💞","cost":120},
  {"id":"simbolo-13","name":"Corazón latiente","kind":"simbolo","emoji":"💓","cost":120},
  {"id":"simbolo-14","name":"Corazón creciente","kind":"simbolo","emoji":"💗","cost":120},
  {"id":"simbolo-15","name":"Corazón brillante","kind":"simbolo","emoji":"💖","cost":160},
  {"id":"simbolo-16","name":"Flechazo","kind":"simbolo","emoji":"💘","cost":160},
  {"id":"simbolo-17","name":"Corazón con lazo","kind":"simbolo","emoji":"💝","cost":160},
  {"id":"simbolo-18","name":"Decoración de corazón","kind":"simbolo","emoji":"💟","cost":220},
  {"id":"simbolo-19","name":"Aries","kind":"simbolo","emoji":"♈","cost":220},
  {"id":"simbolo-20","name":"Tauro","kind":"simbolo","emoji":"♉","cost":220},
  {"id":"simbolo-21","name":"Géminis","kind":"simbolo","emoji":"♊","cost":300},
  {"id":"simbolo-22","name":"Cáncer","kind":"simbolo","emoji":"♋","cost":300},
  {"id":"simbolo-23","name":"Leo","kind":"simbolo","emoji":"♌","cost":300},
  {"id":"simbolo-24","name":"Virgo","kind":"simbolo","emoji":"♍","cost":400},
  {"id":"simbolo-25","name":"Libra","kind":"simbolo","emoji":"♎","cost":400},
  {"id":"simbolo-26","name":"Escorpio","kind":"simbolo","emoji":"♏","cost":400},
  {"id":"simbolo-27","name":"Sagitario","kind":"simbolo","emoji":"♐","cost":400},
  {"id":"simbolo-28","name":"Capricornio","kind":"simbolo","emoji":"♑","cost":400},
  {"id":"simbolo-29","name":"Acuario","kind":"simbolo","emoji":"♒","cost":400},
  {"id":"simbolo-30","name":"Piscis","kind":"simbolo","emoji":"♓","cost":400},
  {"id":"simbolo-31","name":"Reciclaje","kind":"simbolo","emoji":"♻️","cost":400},
  {"id":"simbolo-32","name":"Visto","kind":"simbolo","emoji":"✅","cost":400},
  {"id":"simbolo-33","name":"Destello","kind":"simbolo","emoji":"✴️","cost":400},
  {"id":"simbolo-34","name":"Chispa","kind":"simbolo","emoji":"❇️","cost":400},
  {"id":"simbolo-35","name":"Asterisco","kind":"simbolo","emoji":"✳️","cost":400},
  {"id":"simbolo-36","name":"Cruz verde","kind":"simbolo","emoji":"❎","cost":400},
  {"id":"simbolo-37","name":"Globo con meridianos","kind":"simbolo","emoji":"🌐","cost":400},
  {"id":"simbolo-38","name":"Zzz","kind":"simbolo","emoji":"💤","cost":400},
]
