-- ==================================================================
-- 13_tienda.sql — Tienda (catálogo amplio de ítems + compra genérica)
-- ==================================================================
-- Extraído de supabase/setup_all.sql (sección "TIENDA"), que hasta ahora era
-- la única fuente de verdad para estas tablas/RPCs: quien provisionara una
-- base de datos nueva ejecutando solo migrations/*.sql en orden se quedaba
-- sin tienda, aunque el cliente (StoreClient.tsx, PetStudio.tsx) la da por
-- hecha. Este archivo cierra ese hueco. Ejecutar en el SQL Editor de
-- Supabase después de 09_focus_pet.sql. Es idempotente.

-- ==================================================================
-- TIENDA (catálogo amplio de ítems + compra genérica)
-- ==================================================================
-- store_items es la fuente de verdad del COSTO (el cliente no lo decide). El
-- catálogo se siembra desde src/lib/storeCatalog.ts (mismo listado en código).
create table if not exists public.store_items (
  id    text primary key,
  name  text not null,
  kind  text not null,
  emoji text not null,
  cost  integer not null default 0
);
alter table public.store_items enable row level security;
drop policy if exists "store_items_read" on public.store_items;
create policy "store_items_read" on public.store_items for select using (true);
grant select on public.store_items to anon, authenticated;
revoke insert, update, delete on public.store_items from anon, authenticated;

-- Seed de store_items (generado, 558 ítems).
insert into public.store_items (id, name, kind, emoji, cost) values
  ('gato','Gato','pet','🐱',0),
  ('perro','Perro','pet','🐶',0),
  ('zorro','Zorro','pet','🦊',80),
  ('buho','Búho','pet','🦉',120),
  ('dragon','Dragón','pet','🐉',300),
  ('gorro','Sombrero de copa','hat','🎩',30),
  ('corona','Corona','hat','👑',150),
  ('bufanda','Bufanda','outfit','🧣',40),
  ('capa','Capa de héroe','outfit','🦸',120),
  ('gafas','Gafas de sol','accessory','🕶️',25),
  ('medalla','Medalla','accessory','🏅',60),
  ('pet-0','Conejo','pet','🐰',0),
  ('pet-1','Hámster','pet','🐹',0),
  ('pet-2','Ratón','pet','🐭',20),
  ('pet-3','Oso','pet','🐻',40),
  ('pet-4','Panda','pet','🐼',40),
  ('pet-5','Koala','pet','🐨',40),
  ('pet-6','Tigre','pet','🐯',60),
  ('pet-7','León','pet','🦁',60),
  ('pet-8','Vaca','pet','🐮',60),
  ('pet-9','Cerdito','pet','🐷',90),
  ('pet-10','Rana','pet','🐸',90),
  ('pet-11','Mono','pet','🐵',90),
  ('pet-12','Gallina','pet','🐔',120),
  ('pet-13','Pingüino','pet','🐧',120),
  ('pet-14','Pájaro','pet','🐦',120),
  ('pet-15','Pato','pet','🦆',160),
  ('pet-16','Águila','pet','🦅',160),
  ('pet-17','Murciélago','pet','🦇',160),
  ('pet-18','Lobo','pet','🐺',220),
  ('pet-19','Jabalí','pet','🐗',220),
  ('pet-20','Caballo','pet','🐴',220),
  ('pet-21','Unicornio','pet','🦄',300),
  ('pet-22','Abeja','pet','🐝',300),
  ('pet-23','Mariposa','pet','🦋',300),
  ('pet-24','Caracol','pet','🐌',400),
  ('pet-25','Mariquita','pet','🐞',400),
  ('pet-26','Tortuga','pet','🐢',400),
  ('pet-27','Serpiente','pet','🐍',400),
  ('pet-28','Lagarto','pet','🦎',400),
  ('pet-29','Pulpo','pet','🐙',400),
  ('pet-30','Calamar','pet','🦑',400),
  ('pet-31','Cangrejo','pet','🦀',400),
  ('pet-32','Langosta','pet','🦞',400),
  ('pet-33','Pez tropical','pet','🐠',400),
  ('pet-34','Pececito','pet','🐟',400),
  ('pet-35','Pez globo','pet','🐡',400),
  ('pet-36','Delfín','pet','🐬',400),
  ('pet-37','Ballena','pet','🐳',400),
  ('pet-38','Ballena azul','pet','🐋',400),
  ('pet-39','Tiburón','pet','🦈',400),
  ('pet-40','Leopardo','pet','🐆',400),
  ('pet-41','Tigre de Bengala','pet','🐅',400),
  ('pet-42','Cebra','pet','🦓',400),
  ('pet-43','Gorila','pet','🦍',400),
  ('pet-44','Elefante','pet','🐘',400),
  ('pet-45','Hipopótamo','pet','🦛',400),
  ('pet-46','Rinoceronte','pet','🦏',400),
  ('pet-47','Dromedario','pet','🐪',400),
  ('pet-48','Camello','pet','🐫',400),
  ('pet-49','Jirafa','pet','🦒',400),
  ('pet-50','Canguro','pet','🦘',400),
  ('pet-51','Toro','pet','🐂',400),
  ('pet-52','Vaca lechera','pet','🐄',400),
  ('pet-53','Corcel','pet','🐎',400),
  ('pet-54','Cochinillo','pet','🐖',400),
  ('pet-55','Carnero','pet','🐏',400),
  ('pet-56','Oveja','pet','🐑',400),
  ('pet-57','Llama','pet','🦙',400),
  ('pet-58','Cabra','pet','🐐',400),
  ('pet-59','Ciervo','pet','🦌',400),
  ('pet-60','Caniche','pet','🐩',400),
  ('pet-61','Mapache','pet','🦝',400),
  ('pet-62','Mofeta','pet','🦨',400),
  ('pet-63','Tejón','pet','🦡',400),
  ('pet-64','Nutria','pet','🦦',400),
  ('pet-65','Perezoso','pet','🦥',400),
  ('pet-66','Ardilla','pet','🐿️',400),
  ('pet-67','Erizo','pet','🦔',400),
  ('pet-68','Pavo real','pet','🦚',400),
  ('pet-69','Loro','pet','🦜',400),
  ('pet-70','Cisne','pet','🦢',400),
  ('pet-71','Flamenco','pet','🦩',400),
  ('pet-72','Paloma','pet','🕊️',400),
  ('pet-73','Conejito','pet','🐇',400),
  ('hat-0','Birrete','hat','🎓',20),
  ('hat-1','Casco de rescate','hat','⛑️',20),
  ('hat-2','Casco militar','hat','🪖',20),
  ('hat-3','Gorra','hat','🧢',40),
  ('hat-4','Pamela','hat','👒',40),
  ('hat-5','Calabaza','hat','🎃',40),
  ('hat-6','Antiparras','hat','🥽',60),
  ('hat-7','Lazo','hat','🎀',60),
  ('hat-8','Alien','hat','👽',60),
  ('hat-9','Robot','hat','🤖',90),
  ('hat-10','Cerebro','hat','🧠',90),
  ('hat-11','Flor de cerezo','hat','🌸',90),
  ('hat-12','Hibisco','hat','🌺',120),
  ('hat-13','Girasol','hat','🌻',120),
  ('hat-14','Seta','hat','🍄',120),
  ('hat-15','Estrella','hat','⭐',160),
  ('hat-16','Destellos','hat','✨',160),
  ('hat-17','Estrella fugaz','hat','💫',160),
  ('hat-18','Llama','hat','🔥',220),
  ('hat-19','Copo de nieve','hat','❄️',220),
  ('hat-20','Aureola','hat','😇',220),
  ('hat-21','Querubín','hat','👼',300),
  ('hat-22','Mago','hat','🧙',300),
  ('hat-23','Vampiro','hat','🧛',300),
  ('hat-24','Sirena','hat','🧜',400),
  ('hat-25','Hada','hat','🧚',400),
  ('hat-26','Tengu','hat','👺',400),
  ('hat-27','Ogro','hat','👹',400),
  ('hat-28','Vaquero','hat','🤠',400),
  ('hat-29','Ninja','hat','🥷',400),
  ('hat-30','Papá Noel','hat','🎅',400),
  ('hat-31','Mamá Noel','hat','🤶',400),
  ('outfit-0','Bata','outfit','🥼',20),
  ('outfit-1','Kimono','outfit','🥋',20),
  ('outfit-2','Corbata','outfit','👔',20),
  ('outfit-3','Camiseta','outfit','👕',40),
  ('outfit-4','Vestido','outfit','👗',40),
  ('outfit-5','Kimono floral','outfit','👘',40),
  ('outfit-6','Sari','outfit','🥻',60),
  ('outfit-7','Bañador','outfit','🩱',60),
  ('outfit-8','Bikini','outfit','👙',60),
  ('outfit-9','Blusa','outfit','👚',90),
  ('outfit-10','Abrigo','outfit','🧥',90),
  ('outfit-11','Pantalón corto','outfit','🩳',90),
  ('outfit-12','Vaqueros','outfit','👖',120),
  ('outfit-13','Atletismo','outfit','🎽',120),
  ('outfit-14','Chaleco','outfit','🦺',120),
  ('outfit-15','Calcetines','outfit','🧦',160),
  ('outfit-16','Ropa interior','outfit','🩲',160),
  ('outfit-17','Monedero','outfit','👛',160),
  ('outfit-18','Bolso','outfit','👜',220),
  ('outfit-19','Mochila','outfit','🎒',220),
  ('outfit-20','Guantes','outfit','🧤',220),
  ('outfit-21','Arcoíris','outfit','🌈',300),
  ('outfit-22','Escudo novato','outfit','🔰',300),
  ('outfit-23','Roseta','outfit','🏵️',300),
  ('accessory-0','Gafas','accessory','👓',20),
  ('accessory-1','Oro','accessory','🥇',20),
  ('accessory-2','Plata','accessory','🥈',20),
  ('accessory-3','Bronce','accessory','🥉',40),
  ('accessory-4','Anillo','accessory','💍',40),
  ('accessory-5','Collar','accessory','📿',40),
  ('accessory-6','Diamante','accessory','💎',60),
  ('accessory-7','Bola de cristal','accessory','🔮',60),
  ('accessory-8','Reloj','accessory','⌚',60),
  ('accessory-9','Móvil','accessory','📱',90),
  ('accessory-10','Auriculares','accessory','🎧',90),
  ('accessory-11','Mando','accessory','🎮',90),
  ('accessory-12','Joystick','accessory','🕹️',120),
  ('accessory-13','Dado','accessory','🎲',120),
  ('accessory-14','Comodín','accessory','🃏',120),
  ('accessory-15','Diana','accessory','🎯',160),
  ('accessory-16','Varita mágica','accessory','🪄',160),
  ('accessory-17','Daga','accessory','🗡️',160),
  ('accessory-18','Escudo','accessory','🛡️',220),
  ('accessory-19','Espadas','accessory','⚔️',220),
  ('accessory-20','Arco','accessory','🏹',220),
  ('accessory-21','Tridente','accessory','🔱',300),
  ('accessory-22','Flor de lis','accessory','⚜️',300),
  ('accessory-23','Condecoración','accessory','🎖️',300),
  ('aura-0','Estrella brillante','aura','🌟',20),
  ('aura-1','Explosión','aura','💥',20),
  ('aura-2','Rayo','aura','⚡',20),
  ('aura-3','Ola','aura','🌊',40),
  ('aura-4','Ráfaga','aura','💨',40),
  ('aura-5','Espiral','aura','🌀',40),
  ('aura-6','Tornado','aura','🌪️',60),
  ('aura-7','Burbujas','aura','🫧',60),
  ('aura-8','Gota','aura','💧',60),
  ('aura-9','Gota carmesí','aura','🩸',90),
  ('aura-10','Cometa','aura','☄️',90),
  ('aura-11','Deseo estelar','aura','🌠',90),
  ('aura-12','Fuegos artificiales','aura','🎆',120),
  ('aura-13','Bengala','aura','🎇',120),
  ('aura-14','Vela','aura','🕯️',120),
  ('aura-15','Rombo','aura','💠',160),
  ('aura-16','Brillo intenso','aura','🔆',160),
  ('aura-17','Brillo tenue','aura','🔅',160),
  ('aura-18','Vapor','aura','♨️',220),
  ('fondo-0','Volcán','fondo','🌋',20),
  ('fondo-1','Montaña nevada','fondo','🏔️',20),
  ('fondo-2','Montaña','fondo','⛰️',20),
  ('fondo-3','Vía Láctea','fondo','🌌',40),
  ('fondo-4','Parque natural','fondo','🏞️',40),
  ('fondo-5','Desierto','fondo','🏜️',40),
  ('fondo-6','Atardecer urbano','fondo','🌇',60),
  ('fondo-7','Ciudad al anochecer','fondo','🌆',60),
  ('fondo-8','Skyline','fondo','🏙️',60),
  ('fondo-9','Noche estrellada','fondo','🌃',90),
  ('fondo-10','Puente nocturno','fondo','🌉',90),
  ('fondo-11','Isla','fondo','🏝️',90),
  ('fondo-12','Campamento','fondo','🏕️',120),
  ('fondo-13','Castillo','fondo','🏰',120),
  ('fondo-14','Castillo japonés','fondo','🏯',120),
  ('fondo-15','Torre','fondo','🗼',160),
  ('fondo-16','Amanecer','fondo','🌅',160),
  ('fondo-17','Alba en montaña','fondo','🌄',160),
  ('fondo-18','Niebla','fondo','🌁',220),
  ('fondo-19','Planeta','fondo','🪐',220),
  ('fondo-20','Planeta Tierra','fondo','🌏',220),
  ('fondo-21','Luna','fondo','🌙',300),
  ('insignia-0','Trofeo','insignia','🏆',20),
  ('insignia-1','Cien puntos','insignia','💯',20),
  ('insignia-2','Lazo conmemorativo','insignia','🎗️',20),
  ('insignia-3','Picas','insignia','♠️',40),
  ('insignia-4','Corazones','insignia','♥️',40),
  ('insignia-5','Diamantes','insignia','♦️',40),
  ('insignia-6','Tréboles','insignia','♣️',60),
  ('insignia-7','Dragón rojo','insignia','🀄',60),
  ('insignia-8','Yin y yang','insignia','☯️',60),
  ('insignia-9','Om','insignia','🕉️',90),
  ('insignia-10','Cruz','insignia','✝️',90),
  ('insignia-11','Media luna','insignia','☪️',90),
  ('insignia-12','Estrella de seis puntas','insignia','🔯',120),
  ('insignia-13','Lugar de culto','insignia','🛐',120),
  ('insignia-14','Átomo','insignia','⚛️',120),
  ('comida-0','Manzana','comida','🍎',20),
  ('comida-1','Pizza','comida','🍕',20),
  ('comida-2','Hamburguesa','comida','🍔',20),
  ('comida-3','Papas fritas','comida','🍟',40),
  ('comida-4','Perrito caliente','comida','🌭',40),
  ('comida-5','Palomitas','comida','🍿',40),
  ('comida-6','Sal','comida','🧂',60),
  ('comida-7','Tocino','comida','🥓',60),
  ('comida-8','Panqueques','comida','🥞',60),
  ('comida-9','Gofre','comida','🧇',90),
  ('comida-10','Huevo frito','comida','🍳',90),
  ('comida-11','Huevo','comida','🥚',90),
  ('comida-12','Queso','comida','🧀',120),
  ('comida-13','Pretzel','comida','🥨',120),
  ('comida-14','Cruasán','comida','🥐',120),
  ('comida-15','Baguette','comida','🥖',160),
  ('comida-16','Pan','comida','🍞',160),
  ('comida-17','Rosca','comida','🥯',160),
  ('comida-18','Ramen','comida','🍜',220),
  ('comida-19','Guiso','comida','🍲',220),
  ('comida-20','Curry','comida','🍛',220),
  ('comida-21','Langostino','comida','🍤',300),
  ('comida-22','Onigiri','comida','🍙',300),
  ('comida-23','Arroz','comida','🍚',300),
  ('comida-24','Galleta de arroz','comida','🍘',400),
  ('comida-25','Oden','comida','🍢',400),
  ('comida-26','Dango','comida','🍡',400),
  ('comida-27','Raspado','comida','🍧',400),
  ('comida-28','Helado','comida','🍨',400),
  ('comida-29','Cucurucho','comida','🍦',400),
  ('comida-30','Tarta','comida','🥧',400),
  ('comida-31','Magdalena','comida','🧁',400),
  ('comida-32','Pastel','comida','🍰',400),
  ('comida-33','Tarta de cumpleaños','comida','🎂',400),
  ('comida-34','Flan','comida','🍮',400),
  ('comida-35','Piruleta','comida','🍭',400),
  ('comida-36','Caramelo','comida','🍬',400),
  ('comida-37','Chocolate','comida','🍫',400),
  ('comida-38','Dona','comida','🍩',400),
  ('comida-39','Galleta','comida','🍪',400),
  ('comida-40','Castaña','comida','🌰',400),
  ('comida-41','Cacahuete','comida','🥜',400),
  ('comida-42','Miel','comida','🍯',400),
  ('comida-43','Leche','comida','🥛',400),
  ('comida-44','Café','comida','☕',400),
  ('comida-45','Té','comida','🍵',400),
  ('comida-46','Zumo','comida','🧃',400),
  ('comida-47','Refresco','comida','🥤',400),
  ('comida-48','Té de burbujas','comida','🧋',400),
  ('comida-49','Cerveza','comida','🍺',400),
  ('comida-50','Vino','comida','🍷',400),
  ('comida-51','Brindis','comida','🥂',400),
  ('comida-52','Cóctel','comida','🍸',400),
  ('comida-53','Tropical','comida','🍹',400),
  ('comida-54','Taco','comida','🌮',400),
  ('comida-55','Burrito','comida','🌯',400),
  ('comida-56','Tamal','comida','🫔',400),
  ('comida-57','Pita','comida','🥙',400),
  ('comida-58','Falafel','comida','🧆',400),
  ('comida-59','Sushi','comida','🍣',400),
  ('comida-60','Bento','comida','🍱',400),
  ('comida-61','Uvas','comida','🍇',400),
  ('comida-62','Melón','comida','🍈',400),
  ('comida-63','Sandía','comida','🍉',400),
  ('comida-64','Naranja','comida','🍊',400),
  ('comida-65','Limón','comida','🍋',400),
  ('comida-66','Plátano','comida','🍌',400),
  ('comida-67','Piña','comida','🍍',400),
  ('comida-68','Mango','comida','🥭',400),
  ('comida-69','Pera','comida','🍐',400),
  ('comida-70','Melocotón','comida','🍑',400),
  ('comida-71','Cerezas','comida','🍒',400),
  ('comida-72','Fresa','comida','🍓',400),
  ('comida-73','Arándanos','comida','🫐',400),
  ('comida-74','Kiwi','comida','🥝',400),
  ('comida-75','Tomate','comida','🍅',400),
  ('comida-76','Aceituna','comida','🫒',400),
  ('comida-77','Coco','comida','🥥',400),
  ('comida-78','Aguacate','comida','🥑',400),
  ('comida-79','Berenjena','comida','🍆',400),
  ('comida-80','Patata','comida','🥔',400),
  ('comida-81','Zanahoria','comida','🥕',400),
  ('comida-82','Maíz','comida','🌽',400),
  ('comida-83','Chile','comida','🌶️',400),
  ('comida-84','Pimiento','comida','🫑',400),
  ('comida-85','Pepino','comida','🥒',400),
  ('comida-86','Lechuga','comida','🥬',400),
  ('comida-87','Brócoli','comida','🥦',400),
  ('comida-88','Ajo','comida','🧄',400),
  ('comida-89','Cebolla','comida','🧅',400),
  ('planta-0','Brote','planta','🌱',20),
  ('planta-1','Hierba','planta','🌿',20),
  ('planta-2','Trébol','planta','🍀',20),
  ('planta-3','Espiga','planta','🌾',40),
  ('planta-4','Cactus','planta','🌵',40),
  ('planta-5','Palmera','planta','🌴',40),
  ('planta-6','Pino','planta','🌲',60),
  ('planta-7','Árbol','planta','🌳',60),
  ('planta-8','Tanabata','planta','🎋',60),
  ('planta-9','Bambú','planta','🎍',90),
  ('planta-10','Hoja de arce','planta','🍁',90),
  ('planta-11','Hojas secas','planta','🍂',90),
  ('planta-12','Hojas al viento','planta','🍃',120),
  ('planta-13','Tulipán','planta','🌷',120),
  ('planta-14','Rosa','planta','🌹',120),
  ('planta-15','Rosa marchita','planta','🥀',160),
  ('planta-16','Margarita','planta','🌼',160),
  ('planta-17','Ramo','planta','💐',160),
  ('planta-18','Maceta','planta','🪴',220),
  ('deporte-0','Fútbol','deporte','⚽',20),
  ('deporte-1','Baloncesto','deporte','🏀',20),
  ('deporte-2','Fútbol americano','deporte','🏈',20),
  ('deporte-3','Béisbol','deporte','⚾',40),
  ('deporte-4','Softbol','deporte','🥎',40),
  ('deporte-5','Tenis','deporte','🎾',40),
  ('deporte-6','Voleibol','deporte','🏐',60),
  ('deporte-7','Rugby','deporte','🏉',60),
  ('deporte-8','Disco volador','deporte','🥏',60),
  ('deporte-9','Billar','deporte','🎱',90),
  ('deporte-10','Yoyó','deporte','🪀',90),
  ('deporte-11','Ping-pong','deporte','🏓',90),
  ('deporte-12','Bádminton','deporte','🏸',120),
  ('deporte-13','Portería','deporte','🥅',120),
  ('deporte-14','Hockey','deporte','🏒',120),
  ('deporte-15','Hockey hierba','deporte','🏑',160),
  ('deporte-16','Lacrosse','deporte','🥍',160),
  ('deporte-17','Críquet','deporte','🏏',160),
  ('deporte-18','Bumerán','deporte','🪃',220),
  ('deporte-19','Boxeo','deporte','🥊',220),
  ('deporte-20','Monopatín','deporte','🛹',220),
  ('deporte-21','Patines','deporte','🛼',300),
  ('deporte-22','Trineo','deporte','🛷',300),
  ('deporte-23','Patinaje','deporte','⛸️',300),
  ('deporte-24','Curling','deporte','🥌',400),
  ('deporte-25','Esquí','deporte','🎿',400),
  ('deporte-26','Esquiador','deporte','⛷️',400),
  ('deporte-27','Snowboard','deporte','🏂',400),
  ('deporte-28','Pesas','deporte','🏋️',400),
  ('deporte-29','Lucha','deporte','🤼',400),
  ('deporte-30','Gimnasia','deporte','🤸',400),
  ('deporte-31','Esgrima','deporte','🤺',400),
  ('deporte-32','Balonmano','deporte','🤾',400),
  ('deporte-33','Golf','deporte','🏌️',400),
  ('deporte-34','Hípica','deporte','🏇',400),
  ('deporte-35','Yoga','deporte','🧘',400),
  ('deporte-36','Surf','deporte','🏄',400),
  ('deporte-37','Natación','deporte','🏊',400),
  ('deporte-38','Waterpolo','deporte','🤽',400),
  ('deporte-39','Remo','deporte','🚣',400),
  ('deporte-40','Escalada','deporte','🧗',400),
  ('deporte-41','Ciclismo de montaña','deporte','🚵',400),
  ('deporte-42','Ciclismo','deporte','🚴',400),
  ('musica-0','Nota musical','musica','🎵',20),
  ('musica-1','Melodía','musica','🎶',20),
  ('musica-2','Partitura','musica','🎼',20),
  ('musica-3','Micrófono','musica','🎤',40),
  ('musica-4','Saxofón','musica','🎷',40),
  ('musica-5','Guitarra','musica','🎸',40),
  ('musica-6','Piano','musica','🎹',60),
  ('musica-7','Trompeta','musica','🎺',60),
  ('musica-8','Violín','musica','🎻',60),
  ('musica-9','Banjo','musica','🪕',90),
  ('musica-10','Batería','musica','🥁',90),
  ('musica-11','Tambor','musica','🪘',90),
  ('musica-12','Corneta','musica','📯',120),
  ('musica-13','Micrófono de estudio','musica','🎙️',120),
  ('musica-14','Ecualizador','musica','🎚️',120),
  ('musica-15','Mesa de mezclas','musica','🎛️',160),
  ('objeto-0','Bombilla','objeto','💡',20),
  ('objeto-1','Linterna','objeto','🔦',20),
  ('objeto-2','Lámpara de aceite','objeto','🪔',20),
  ('objeto-3','Llave inglesa','objeto','🔧',40),
  ('objeto-4','Martillo','objeto','🔨',40),
  ('objeto-5','Martillo y pico','objeto','⚒️',40),
  ('objeto-6','Herramientas','objeto','🛠️',60),
  ('objeto-7','Pico','objeto','⛏️',60),
  ('objeto-8','Tornillo','objeto','🔩',60),
  ('objeto-9','Engranaje','objeto','⚙️',90),
  ('objeto-10','Caja de herramientas','objeto','🧰',90),
  ('objeto-11','Imán','objeto','🧲',90),
  ('objeto-12','Pistola de agua','objeto','🔫',120),
  ('objeto-13','Bomba','objeto','💣',120),
  ('objeto-14','Petardo','objeto','🧨',120),
  ('objeto-15','Hacha','objeto','🪓',160),
  ('objeto-16','Cuchillo','objeto','🔪',160),
  ('objeto-17','Humo','objeto','🚬',160),
  ('objeto-18','Ataúd','objeto','⚰️',220),
  ('objeto-19','Urna','objeto','⚱️',220),
  ('objeto-20','Ánfora','objeto','🏺',220),
  ('objeto-21','Ojo turco','objeto','🧿',300),
  ('objeto-22','Barbería','objeto','💈',300),
  ('objeto-23','Alambique','objeto','⚗️',300),
  ('objeto-24','Telescopio','objeto','🔭',400),
  ('objeto-25','Microscopio','objeto','🔬',400),
  ('objeto-26','Agujero','objeto','🕳️',400),
  ('objeto-27','Pastilla','objeto','💊',400),
  ('objeto-28','Jeringa','objeto','💉',400),
  ('objeto-29','ADN','objeto','🧬',400),
  ('objeto-30','Microbio','objeto','🦠',400),
  ('objeto-31','Placa Petri','objeto','🧫',400),
  ('objeto-32','Probeta','objeto','🧪',400),
  ('objeto-33','Termómetro','objeto','🌡️',400),
  ('objeto-34','Escoba','objeto','🧹',400),
  ('objeto-35','Cesta','objeto','🧺',400),
  ('objeto-36','Papel','objeto','🧻',400),
  ('objeto-37','Campanilla','objeto','🛎️',400),
  ('objeto-38','Llave','objeto','🔑',400),
  ('objeto-39','Llave antigua','objeto','🗝️',400),
  ('objeto-40','Puerta','objeto','🚪',400),
  ('objeto-41','Silla','objeto','🪑',400),
  ('objeto-42','Sofá','objeto','🛋️',400),
  ('objeto-43','Cama','objeto','🛏️',400),
  ('objeto-44','Osito de peluche','objeto','🧸',400),
  ('objeto-45','Cuadro','objeto','🖼️',400),
  ('objeto-46','Espejo','objeto','🪞',400),
  ('objeto-47','Bolsas','objeto','🛍️',400),
  ('objeto-48','Carrito','objeto','🛒',400),
  ('objeto-49','Regalo','objeto','🎁',400),
  ('objeto-50','Globo','objeto','🎈',400),
  ('objeto-51','Banderines koi','objeto','🎏',400),
  ('objeto-52','Confeti','objeto','🎊',400),
  ('objeto-53','Fiesta','objeto','🎉',400),
  ('objeto-54','Piñata','objeto','🪅',400),
  ('objeto-55','Matrioska','objeto','🪆',400),
  ('objeto-56','Cámara','objeto','📷',400),
  ('objeto-57','Cámara con flash','objeto','📸',400),
  ('objeto-58','Videocámara','objeto','📹',400),
  ('objeto-59','Cinta','objeto','📼',400),
  ('objeto-60','Disquete','objeto','💾',400),
  ('objeto-61','CD','objeto','💿',400),
  ('objeto-62','DVD','objeto','📀',400),
  ('objeto-63','Ábaco','objeto','🧮',400),
  ('objeto-64','Libro rojo','objeto','📕',400),
  ('objeto-65','Libro verde','objeto','📗',400),
  ('objeto-66','Libro azul','objeto','📘',400),
  ('objeto-67','Libro naranja','objeto','📙',400),
  ('objeto-68','Libros','objeto','📚',400),
  ('objeto-69','Libro abierto','objeto','📖',400),
  ('vehiculo-0','Coche','vehiculo','🚗',20),
  ('vehiculo-1','Taxi','vehiculo','🚕',20),
  ('vehiculo-2','Todoterreno','vehiculo','🚙',20),
  ('vehiculo-3','Autobús','vehiculo','🚌',40),
  ('vehiculo-4','Trolebús','vehiculo','🚎',40),
  ('vehiculo-5','Bólido','vehiculo','🏎️',40),
  ('vehiculo-6','Coche de policía','vehiculo','🚓',60),
  ('vehiculo-7','Ambulancia','vehiculo','🚑',60),
  ('vehiculo-8','Camión de bomberos','vehiculo','🚒',60),
  ('vehiculo-9','Furgoneta','vehiculo','🚐',90),
  ('vehiculo-10','Camión','vehiculo','🚚',90),
  ('vehiculo-11','Tráiler','vehiculo','🚛',90),
  ('vehiculo-12','Tractor','vehiculo','🚜',120),
  ('vehiculo-13','Pickup','vehiculo','🛻',120),
  ('vehiculo-14','Moto','vehiculo','🏍️',120),
  ('vehiculo-15','Scooter','vehiculo','🛵',160),
  ('vehiculo-16','Bicicleta','vehiculo','🚲',160),
  ('vehiculo-17','Patinete','vehiculo','🛴',160),
  ('vehiculo-18','Sirena','vehiculo','🚨',220),
  ('vehiculo-19','Patrulla','vehiculo','🚔',220),
  ('vehiculo-20','Autobús que llega','vehiculo','🚍',220),
  ('vehiculo-21','Coche que llega','vehiculo','🚘',300),
  ('vehiculo-22','Taxi que llega','vehiculo','🚖',300),
  ('vehiculo-23','Teleférico','vehiculo','🚡',300),
  ('vehiculo-24','Funicular','vehiculo','🚠',400),
  ('vehiculo-25','Monorraíl suspendido','vehiculo','🚟',400),
  ('vehiculo-26','Vagón','vehiculo','🚃',400),
  ('vehiculo-27','Tranvía','vehiculo','🚋',400),
  ('vehiculo-28','Tren de montaña','vehiculo','🚞',400),
  ('vehiculo-29','Monorraíl','vehiculo','🚝',400),
  ('vehiculo-30','Tren bala','vehiculo','🚄',400),
  ('vehiculo-31','AVE','vehiculo','🚅',400),
  ('vehiculo-32','Tren ligero','vehiculo','🚈',400),
  ('vehiculo-33','Locomotora','vehiculo','🚂',400),
  ('vehiculo-34','Tren','vehiculo','🚆',400),
  ('vehiculo-35','Metro','vehiculo','🚇',400),
  ('vehiculo-36','Tranvía moderno','vehiculo','🚊',400),
  ('vehiculo-37','Estación','vehiculo','🚉',400),
  ('vehiculo-38','Avión','vehiculo','✈️',400),
  ('vehiculo-39','Despegue','vehiculo','🛫',400),
  ('vehiculo-40','Avioneta','vehiculo','🛩️',400),
  ('vehiculo-41','Asiento','vehiculo','💺',400),
  ('vehiculo-42','Helicóptero','vehiculo','🚁',400),
  ('vehiculo-43','Cohete','vehiculo','🚀',400),
  ('vehiculo-44','Platillo volante','vehiculo','🛸',400),
  ('vehiculo-45','Satélite','vehiculo','🛰️',400),
  ('vehiculo-46','Velero','vehiculo','⛵',400),
  ('vehiculo-47','Lancha','vehiculo','🚤',400),
  ('vehiculo-48','Yate','vehiculo','🛥️',400),
  ('vehiculo-49','Crucero','vehiculo','🛳️',400),
  ('vehiculo-50','Ferry','vehiculo','⛴️',400),
  ('vehiculo-51','Barco','vehiculo','🚢',400),
  ('vehiculo-52','Ancla','vehiculo','⚓',400),
  ('vehiculo-53','Gasolinera','vehiculo','⛽',400),
  ('vehiculo-54','Semáforo','vehiculo','🚦',400),
  ('vehiculo-55','Semáforo horizontal','vehiculo','🚥',400),
  ('vehiculo-56','Mapa','vehiculo','🗺️',400),
  ('vehiculo-57','Moái','vehiculo','🗿',400),
  ('vehiculo-58','Estatua de la Libertad','vehiculo','🗽',400),
  ('vehiculo-59','Fuente','vehiculo','⛲',400),
  ('simbolo-0','Corazón rojo','simbolo','❤️',20),
  ('simbolo-1','Corazón naranja','simbolo','🧡',20),
  ('simbolo-2','Corazón amarillo','simbolo','💛',20),
  ('simbolo-3','Corazón verde','simbolo','💚',40),
  ('simbolo-4','Corazón azul','simbolo','💙',40),
  ('simbolo-5','Corazón morado','simbolo','💜',40),
  ('simbolo-6','Corazón negro','simbolo','🖤',60),
  ('simbolo-7','Corazón blanco','simbolo','🤍',60),
  ('simbolo-8','Corazón marrón','simbolo','🤎',60),
  ('simbolo-9','Corazón roto','simbolo','💔',90),
  ('simbolo-10','Corazón exclamación','simbolo','❣️',90),
  ('simbolo-11','Dos corazones','simbolo','💕',90),
  ('simbolo-12','Corazones giratorios','simbolo','💞',120),
  ('simbolo-13','Corazón latiente','simbolo','💓',120),
  ('simbolo-14','Corazón creciente','simbolo','💗',120),
  ('simbolo-15','Corazón brillante','simbolo','💖',160),
  ('simbolo-16','Flechazo','simbolo','💘',160),
  ('simbolo-17','Corazón con lazo','simbolo','💝',160),
  ('simbolo-18','Decoración de corazón','simbolo','💟',220),
  ('simbolo-19','Aries','simbolo','♈',220),
  ('simbolo-20','Tauro','simbolo','♉',220),
  ('simbolo-21','Géminis','simbolo','♊',300),
  ('simbolo-22','Cáncer','simbolo','♋',300),
  ('simbolo-23','Leo','simbolo','♌',300),
  ('simbolo-24','Virgo','simbolo','♍',400),
  ('simbolo-25','Libra','simbolo','♎',400),
  ('simbolo-26','Escorpio','simbolo','♏',400),
  ('simbolo-27','Sagitario','simbolo','♐',400),
  ('simbolo-28','Capricornio','simbolo','♑',400),
  ('simbolo-29','Acuario','simbolo','♒',400),
  ('simbolo-30','Piscis','simbolo','♓',400),
  ('simbolo-31','Reciclaje','simbolo','♻️',400),
  ('simbolo-32','Visto','simbolo','✅',400),
  ('simbolo-33','Destello','simbolo','✴️',400),
  ('simbolo-34','Chispa','simbolo','❇️',400),
  ('simbolo-35','Asterisco','simbolo','✳️',400),
  ('simbolo-36','Cruz verde','simbolo','❎',400),
  ('simbolo-37','Globo con meridianos','simbolo','🌐',400),
  ('simbolo-38','Zzz','simbolo','💤',400)
on conflict (id) do update set name = excluded.name, kind = excluded.kind, emoji = excluded.emoji, cost = excluded.cost;

create table if not exists public.store_owned (
  user_id     uuid not null references auth.users (id) on delete cascade,
  item_id     text not null,
  acquired_at timestamptz not null default now(),
  primary key (user_id, item_id)
);
alter table public.store_owned enable row level security;
drop policy if exists "store_owned_read" on public.store_owned;
create policy "store_owned_read" on public.store_owned for select using (auth.uid() = user_id);
revoke insert, update, delete on public.store_owned from anon, authenticated;

-- Compra genérica: el COSTO lo decide el servidor (store_items). Para ítems
-- equipables también inserta pet_owned, así se pueden lucir en Focus Pet.
create or replace function public.buy_store_item(p_item text)
returns integer as $$
declare v_cost int; v_kind text; v_total int;
begin
  select cost, kind into v_cost, v_kind from public.store_items where id = p_item;
  if v_cost is null then raise exception 'Ítem desconocido: %', p_item; end if;

  if exists (select 1 from public.store_owned where user_id = auth.uid() and item_id = p_item) then
    if v_kind in ('pet','hat','outfit','accessory') then
      insert into public.pet_owned (user_id, item_id) values (auth.uid(), p_item) on conflict do nothing;
    end if;
    return coalesce((select total_points from public.points where user_id = auth.uid()), 0);
  end if;

  if public.is_dev() then
    v_cost := 0;
  else
    select total_points into v_total from public.points where user_id = auth.uid() for update;
    v_total := coalesce(v_total, 0);
    if v_total < v_cost then raise exception 'Puntos insuficientes'; end if;
  end if;

  if v_cost > 0 then
    update public.points set total_points = total_points - v_cost, updated_at = now()
      where user_id = auth.uid();
  end if;

  insert into public.store_owned (user_id, item_id) values (auth.uid(), p_item) on conflict do nothing;
  if v_kind in ('pet','hat','outfit','accessory') then
    insert into public.pet_owned (user_id, item_id) values (auth.uid(), p_item) on conflict do nothing;
  end if;

  return coalesce((select total_points from public.points where user_id = auth.uid()), 0);
end;
$$ language plpgsql security definer set search_path = public;
grant execute on function public.buy_store_item(text) to authenticated;

-- Backfill: lo ya comprado en Focus Pet cuenta como poseído en la tienda.
insert into public.store_owned (user_id, item_id)
  select user_id, item_id from public.pet_owned
  on conflict do nothing;
